// lib/pilots-data.ts

export type PilotLang = "vi" | "en" | "fr" | "ru" | "zh" | "hi";

export interface Pilot {
  slug: string;
  name: string;

  // đa ngôn ngữ
  nickname: Record<PilotLang, string>;

  role: Record<PilotLang, string>;
  experience: Record<PilotLang, string>; // ví dụ: "7 năm"
  flights: Record<PilotLang, string>; // ví dụ: "2000+"
  hours?: Record<PilotLang, string>; // ví dụ: "1000+ giờ"
  phone: string;

  avatar: string;
  hero: string;
  gallery: string[];

  specialties: Record<PilotLang, string[]>;
  certificates: Record<PilotLang, string[]>;

  bio: Record<PilotLang, string>;
  funFacts: Record<PilotLang, string[]>;
  achievements: Record<PilotLang, string[]>;
  flyingStyle: Record<PilotLang, string>;
}

export const pilots: Pilot[] = [
  {
    slug: "dinh-the-anh",
    name: "ĐINH THẾ ANH",
    nickname: {
      vi: "Thợ săn mây",
      en: "Cloud Hunter",
      fr: "Chasseur de Nuages",
      ru: "Охотник за облаками",
      zh: "追云者",
      hi: "बादलों का शिकारी",
    },
    role: {
      vi: "Phi công",
      en: "Pilot",
      fr: "Pilote",
      ru: "Пилот",
      zh: "飞行员",
      hi: "पायलट",
    },
    experience: {
      vi: "Nhiều năm",
      en: "Many years",
      fr: "De nombreuses années",
      ru: "Много лет",
      zh: "多年经验",
      hi: "कई वर्षों का अनुभव",
    },
    flights: {
      vi: "5000+",
      en: "5000+",
      fr: "5000+",
      ru: "5000+",
      zh: "5000+",
      hi: "5000+",
    },
    hours: {
      vi: "1500+ giờ",
      en: "1500+ hours",
      fr: "1500+ heures",
      ru: "1500+ часов",
      zh: "1500+ 小时",
      hi: "1500+ घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/dinh-the-anh/dinh-the-anh.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/dinh-the-anh/hero-1.png",
      "/pilots/dinh-the-anh/hero-2.png",
      "/pilots/dinh-the-anh/hero-3.png",
      "/pilots/dinh-the-anh/hero-4.png",
      "/pilots/dinh-the-anh/hero-5.png",
      "/pilots/dinh-the-anh/content-1.png",
      "/pilots/dinh-the-anh/content-2.png",
      "/pilots/dinh-the-anh/content-3.png",
    ],
    specialties: {
      vi: ["Hạ cánh chính xác", "Nhiếp ảnh gia"],
      en: ["Precision landing", "Photographer"],
      fr: ["Atterrissage de précision", "Photographe"],
      ru: ["Точность приземления", "Фотограф"],
      zh: ["精准降落", "摄影师"],
      hi: ["प्रिसिजन लैंडिंग", "फोटोग्राफ़र"],
    },
    certificates: {
      vi: ["Đại diện Olympic 2023"],
      en: ["Olympics 2023 Representative"],
      fr: ["Représentant aux Jeux Olympiques 2023"],
      ru: ["Представитель на Олимпиаде 2023"],
      zh: ["2023 奥林匹克代表"],
      hi: ["2023 ओलंपिक प्रतिनिधि"],
    },
    bio: {
      vi: "Phi công giàu năng lượng thể thao, từ đua xe đạp, bơi lội đến dù lượn, với trên 5,000 chuyến bay, hơn 1,500 giờ bay an toàn và 3 lần vô địch hạ cánh chính xác tại Việt Nam.",
      en: "A pilot full of sports energy, from cycling, swimming to paragliding, with 5,000 flights, over 1,500 safe flight hours, and 3-time precision landing champion in Vietnam.",
      fr: "Un pilote plein d'énergie sportive, du cyclisme à la natation en passant par le parapente, avec 5,000 vols, plus de 1,500 heures de vol en toute sécurité et 3 fois champion d'atterrissage de précision au Vietnam.",
      ru: "Пилот, полный спортивной энергии: от велоспорта и плавания до парапланеризма. Более 5 000 полётов, свыше 1 500 часов безопасного налёта и 3-кратный чемпион Вьетнама по точности приземления.",
      zh: "充满运动活力的飞行员：从骑行、游泳到滑翔伞。累计 5,000+ 次飞行、1,500+ 小时安全飞行，并 3 次获得越南“精准降落”冠军。",
      hi: "खेलों से भरपूर ऊर्जा वाले पायलट—साइक्लिंग, तैराकी से लेकर पैराग्लाइडिंग तक। 5,000+ उड़ानें, 1,500+ सुरक्षित उड़ान घंटे और वियतनाम में 3 बार प्रिसिजन लैंडिंग चैंपियन।",
    },
    funFacts: {
      vi: [
        "Được mệnh danh là “anh trai quốc dân” – sinh ra và lớn lên tại Đà Nẵng, chàng trai miền Trung mang trong mình nét dịu dàng, ấm áp đúng chất gió biển và nắng vàng quê hương, ấn tượng bởi nụ cười hiền khô và giọng nói trầm ấm, và anh còn khiến bao người “tan chảy” với sự chu đáo và tinh tế trong từng hành động.",
        "Không chỉ bay dù cực đỉnh mà còn là nhiếp ảnh gia chuyên nghiệp luôn đó!",
        "Thế nên khi bay cùng anh, bạn cứ yên tâm là sẽ có rất rất nhiều tấm hình siêu xịn, góc nào cũng đẹp, khoảnh khắc nào cũng đáng nhớ!",
      ],
      en: [
        "Known as the 'national big brother' – born and raised in Da Nang, he embodies the gentle warmth of the sea breeze and golden sun, with a kind smile and a warm deep voice, melting hearts with his thoughtfulness.",
        "Not only an excellent paraglider but also a professional photographer!",
        "So when flying with him, you can be sure you'll get tons of stunning photos—every angle beautiful, every moment memorable!",
      ],
      fr: [
        "Connu comme le 'grand frère national' – né et élevé à Da Nang, il incarne la douceur du vent marin et du soleil, avec un sourire bienveillant et une voix chaleureuse, faisant fondre les cœurs par sa prévenance.",
        "Non seulement un excellent parapentiste, mais aussi un photographe professionnel !",
        "En volant avec lui, vous aurez énormément de photos superbes : chaque angle est magnifique, chaque instant mémorable !",
      ],
      ru: [
        "Известен как «национальный старший брат» — родился и вырос в Дананге. Тёплый, внимательный, с мягкой улыбкой и глубоким голосом.",
        "Не только отлично летает, но и профессионально снимает фото!",
        "С ним у вас будет много крутых кадров: каждый ракурс красивый, каждый момент — незабываемый!",
      ],
      zh: [
        "被称为“国民哥哥”——在岘港长大，温柔又暖心，笑容治愈、声音沉稳，做事细致周到。",
        "不仅飞得稳、还会专业摄影！",
        "和他一起飞，你一定能收获超多高质量照片：角度都好看，瞬间都值得纪念！",
      ],
      hi: [
        "उन्हें “नेशनल बिग ब्रदर” कहा जाता है—दा नांग में जन्मे/पले-बढ़े, समुद्री हवा जैसी गर्मजोशी, सुकूनभरी मुस्कान और गहरी आवाज़; हर छोटी बात में बेहद ध्यान रखने वाले।",
        "शानदार पायलट होने के साथ-साथ प्रोफेशनल फ़ोटोग्राफ़र भी!",
        "उनके साथ उड़ें तो ढेर सारी शानदार तस्वीरें पक्की—हर एंगल खूबसूरत, हर पल यादगार!",
      ],
    },
    achievements: {
      vi: [
        "Thực hiện hơn 5.000 chuyến bay, với tổng thời gian bay an toàn vượt mốc 1.000 giờ.",
        "Đại diện Việt Nam bay thẳng sang Olympic 2023 tại Hàn Quốc.",
        "Ba lần vô địch nội dung hạ cánh chính xác trong các giải đấu quốc gia",
        "Đã từng cất cánh tại nhiều quốc gia trên thế giới như: Thụy Sĩ, Hàn Quốc, Hoa Kỳ, Thái Lan, Indonesia….",
      ],
      en: [
        "Completed over 5,000 flights, with total safe flying time exceeding 1,000 hours.",
        "Represented Vietnam at the 2023 Olympics in Korea.",
        "Three-time national precision landing champion.",
        "Has taken off in many countries: Switzerland, Korea, USA, Thailand, Indonesia...",
      ],
      fr: [
        "Plus de 5 000 vols, avec un temps de vol en sécurité dépassant 1 000 heures.",
        "A représenté le Vietnam aux Jeux Olympiques 2023 en Corée.",
        "Triple champion national d'atterrissage de précision.",
        "A décollé dans de nombreux pays : Suisse, Corée, États-Unis, Thaïlande, Indonésie...",
      ],
      ru: [
        "Более 5 000 полётов и свыше 1 000 часов безопасного налёта.",
        "Представлял Вьетнам на Олимпийских играх 2023 года в Корее.",
        "Трёхкратный чемпион по точности приземления на национальных соревнованиях.",
        "Летал в разных странах: Швейцария, Корея, США, Таиланд, Индонезия...",
      ],
      zh: [
        "累计 5,000+ 次飞行，安全飞行时长 1,000+ 小时。",
        "代表越南参加 2023 韩国奥林匹克赛事相关飞行活动。",
        "3 次获得全国“精准降落”冠军。",
        "在瑞士、韩国、美国、泰国、印尼等多国起飞飞行。",
      ],
      hi: [
        "5,000+ उड़ानें और 1,000+ सुरक्षित उड़ान घंटे।",
        "2023 कोरिया ओलंपिक इवेंट में वियतनाम का प्रतिनिधित्व।",
        "नेशनल प्रिसिजन लैंडिंग में 3 बार चैंपियन।",
        "स्विट्ज़रलैंड, कोरिया, USA, थाईलैंड, इंडोनेशिया आदि कई देशों में उड़ान अनुभव।",
      ],
    },
    flyingStyle: {
      vi: "Phi công giàu năng lượng thể thao, 3 lần vô địch hạ cánh chính xác.",
      en: "A pilot full of sports energy, 3-time precision landing champion.",
      fr: "Pilote plein d'énergie sportive, triple champion d'atterrissage de précision.",
      ru: "Спортивный пилот, 3-кратный чемпион по точности приземления.",
      zh: "运动型飞行员，三届精准降落冠军，飞行稳、控制细腻。",
      hi: "स्पोर्ट्स एनर्जी से भरपूर, 3 बार प्रिसिजन लैंडिंग चैंपियन—बहुत स्थिर और सटीक उड़ान।",
    },
  },

  {
    slug: "tuan-nguyen",
    name: "TUẤN NGUYỄN",
    nickname: {
      vi: "Nhị ca",
      en: "Nhi Ca",
      fr: "Nhi Ca",
      ru: "Ни Ка",
      zh: "二哥",
      hi: "नि का",
    },
    role: {
      vi: "Phi công PG & PPG",
      en: "Paragliding & Powered Paragliding Pilot",
      fr: "Pilote parapente & paramoteur",
      ru: "Пилот параплана и парамотора",
      zh: "滑翔伞/动力伞飞行员",
      hi: "पैराग्लाइडिंग व पावर्ड पैराग्लाइडिंग पायलट",
    },
    experience: {
      vi: "Nhiều năm",
      en: "Many years",
      fr: "De nombreuses années",
      ru: "Много лет",
      zh: "多年经验",
      hi: "कई वर्षों का अनुभव",
    },
    flights: {
      vi: "3000+",
      en: "3000+",
      fr: "3000+",
      ru: "3000+",
      zh: "3000+",
      hi: "3000+",
    },
    hours: {
      vi: "Nhiều giờ",
      en: "Many hours",
      fr: "De nombreuses heures",
      ru: "Много часов",
      zh: "许多小时",
      hi: "कई घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/tuan-nguyen/tuan-nguyen.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/tuan-nguyen/hero-1.png",
      "/pilots/tuan-nguyen/hero-2.png",
      "/pilots/tuan-nguyen/hero-3.png",
      "/pilots/tuan-nguyen/hero-4.png",
      "/pilots/tuan-nguyen/hero-5.png",
      "/pilots/tuan-nguyen/content-1.png",
      "/pilots/tuan-nguyen/content-2.png",
      "/pilots/tuan-nguyen/content-3.png",
    ],
    specialties: {
      vi: ["Bay êm ái", "Bay với trẻ em", "Đào tạo"],
      en: ["Smooth flights", "Flying with children", "Training"],
      fr: ["Vols en douceur", "Vol avec enfants", "Formation"],
      ru: ["Плавный полёт", "Полёт с детьми", "Обучение"],
      zh: ["飞行顺滑", "亲子飞行", "培训"],
      hi: ["स्मूद फ्लाइट", "बच्चों के साथ उड़ान", "ट्रेनिंग"],
    },
    certificates: {
      vi: [],
      en: [],
      fr: [],
      ru: [],
      zh: [],
      hi: [],
    },
    bio: {
      vi: "Phi công nhẹ nhàng, ân cần, luôn lắng nghe yêu cầu khách. Bạn thích bay mạnh tay hay “chill” nhẹ nhàng, anh đều có cách chọn góc quay và đường bay siêu phê đắm, đảm bảo bay xong ai cũng muốn… làm fan cứng!",
      en: "A gentle, caring pilot who always listens to customer requests. Whether you like acrobatic flying or a gentle 'chill' ride, he chooses camera angles and flight paths that feel amazing—after the flight, everyone becomes a loyal fan!",
      fr: "Un pilote doux et attentionné qui écoute toujours les demandes. Vol dynamique ou balade 'chill', il sait choisir les bons angles et trajectoires—après le vol, tout le monde devient fan !",
      ru: "Нежный и заботливый пилот, всегда прислушивается к пожеланиям. Хотите драйва или спокойного «чилла» — подберёт траекторию и ракурсы так, что после полёта все становятся фанатами!",
      zh: "温柔细心、特别会倾听需求的飞行员。想刺激还是轻松“chill”，他都能安排最舒服的航线和拍摄角度，让你飞完直接变铁粉！",
      hi: "बहुत ही सौम्य और ध्यान रखने वाले पायलट—आपकी पसंद सुनकर उड़ान सेट करते हैं। आपको तेज़ स्टाइल चाहिए या आरामदायक ‘chill’—वो बेहतरीन फ्लाइट पाथ और कैमरा एंगल चुनते हैं; उड़ान के बाद सब उनके फैन बन जाते हैं!",
    },
    funFacts: {
      vi: [
        'Biệt danh mang đậm tính kiếm hiệp " Nhị ca" nhưng tính cách anh vô cùng thân thiện và dễ thương. Anh yêu quý các bạn nhỏ và sau mỗi chuyến bay tất cả các chiến thiên thần đều nhớ chú phi công dễ thương và viết thư tặng chú.',
        "Nếu cha mẹ đang tìm một người đàn ông chỉn chu, tận tâm tràn năng lượng tích cực để đồng hành cùng bé yêu trên hành trình chạm mây — thì không ai khác, Nhị ca chính là lựa chọn tuyệt vời!",
      ],
      en: [
        "His nickname 'Nhi Ca' sounds like it's from a martial arts movie, but he's extremely friendly and sweet. He loves children—many kids even write him letters after flying.",
        "If parents want a neat, dedicated man full of positive energy to accompany their kid—Nhi Ca is the perfect choice!",
      ],
      fr: [
        "Son surnom 'Nhi Ca' semble sorti d'un film d'arts martiaux, mais il est très amical et adorable. Il adore les enfants—beaucoup lui écrivent après le vol.",
        "Pour accompagner votre enfant avec énergie positive et bienveillance, Nhi Ca est le choix parfait !",
      ],
      ru: [
        "Прозвище «Ни Ка» звучит как из боевика, но он очень дружелюбный и милый. Любит детей — после полётов они даже пишут ему письма.",
        "Для родителей, которые хотят заботливого и позитивного пилота для ребёнка — Ни Ка идеален!",
      ],
      zh: [
        "外号“二哥”很武侠，但人特别亲切可爱；很喜欢小朋友，很多孩子飞完还会写信送给他。",
        "如果家长想找一个认真、靠谱、满满正能量的人陪孩子“触摸云朵”，二哥就是最佳选择！",
      ],
      hi: [
        "‘नि का’ नाम थोड़ा मार्शल-आर्ट्स मूवी जैसा लगता है, लेकिन उनका स्वभाव बेहद दोस्ताना और प्यारा है। उन्हें बच्चे बहुत पसंद हैं—कई बच्चे उड़ान के बाद उन्हें पत्र भी लिखते हैं।",
        "अगर माता-पिता अपने बच्चे के लिए सकारात्मक ऊर्जा वाले, जिम्मेदार और केयरिंग पायलट की तलाश में हैं—तो नि का परफेक्ट चॉइस हैं!",
      ],
    },
    achievements: {
      vi: [
        "Đã thực hiện thành công hơn 3.000 chuyến bay tandem an toàn tại Việt Nam.",
        "Hiểu biết sâu về khí tượng tại các điểm bay trên toàn quốc, với khả năng đánh giá và dự báo thời tiết chính xác phục vụ cho hoạt động bay.",
        "Thuần thục kỹ năng bay dù lượn không động cơ và có động cơ.",
        "Là hướng dẫn viên dù lượn chuyên nghiệp, đã đào tạo và đồng hành cùng nhiều phi công trên hành trình chinh phục bầu trời Việt Nam.",
      ],
      en: [
        "Successfully completed over 3,000 safe tandem flights in Vietnam.",
        "Deep meteorology knowledge across Vietnam’s flight sites; accurate weather assessment and forecasting for operations.",
        "Skilled in both unpowered and powered paragliding.",
        "Professional instructor—trained and accompanied many pilots in Vietnam.",
      ],
      fr: [
        "Plus de 3 000 vols tandem effectués en toute sécurité au Vietnam.",
        "Excellente connaissance de la météo sur les sites de vol; évaluation et prévision précises.",
        "Maîtrise du parapente motorisé et non motorisé.",
        "Instructeur professionnel—formation et accompagnement de nombreux pilotes.",
      ],
      ru: [
        "Более 3 000 безопасных тандемных полётов во Вьетнаме.",
        "Глубокие знания метеоусловий на точках полётов по стране; точная оценка и прогноз.",
        "Владеет навыками безмоторного и моторного парапланеризма.",
        "Профессиональный инструктор—обучил и сопровождал многих пилотов.",
      ],
      zh: [
        "在越南完成 3,000+ 次安全双人飞行。",
        "对全国各飞行点气象非常熟悉，能精准评估与预测飞行天气。",
        "熟练掌握无动力与动力伞飞行技能。",
        "专业教练，培训并陪伴许多飞行员成长。",
      ],
      hi: [
        "वियतनाम में 3,000+ सुरक्षित टैंडम उड़ानें सफलतापूर्वक पूरी कीं।",
        "देशभर के फ्लाइंग स्पॉट्स की मौसम-विज्ञान समझ—सटीक आकलन/पूर्वानुमान।",
        "नॉन-पावर्ड और पावर्ड—दोनों पैराग्लाइडिंग में दक्ष।",
        "प्रोफेशनल इंस्ट्रक्टर—कई पायलट्स को ट्रेन किया और मार्गदर्शन दिया।",
      ],
    },
    flyingStyle: {
      vi: "Nhẹ nhàng, ân cần, luôn lắng nghe yêu cầu khách. Bay mạnh hay 'chill' đều được.",
      en: "Gentle and attentive—can do both dynamic and chill flights based on your preference.",
      fr: "Doux et attentionné—vol dynamique ou 'chill' selon vos envies.",
      ru: "Нежный и внимательный—и драйв, и спокойный «чилл» по желанию.",
      zh: "温柔细致，按你的喜好安排：刺激或轻松都可以。",
      hi: "सौम्य और केयरिंग—आप चाहें तो डायनेमिक या आरामदायक ‘chill’ दोनों तरह की उड़ान।",
    },
  },

  {
    slug: "minh-trung",
    name: "MINH TRUNG",
    nickname: {
      vi: "Chiến thần không gian",
      en: "Space Warrior",
      fr: "Guerrier de l'Espace",
      ru: "Космический воин",
      zh: "太空战神",
      hi: "स्पेस वॉरियर",
    },
    role: {
      vi: "Phi công",
      en: "Pilot",
      fr: "Pilote",
      ru: "Пилот",
      zh: "飞行员",
      hi: "पायलट",
    },
    experience: {
      vi: "7 năm",
      en: "7 years",
      fr: "7 ans",
      ru: "7 лет",
      zh: "7 年",
      hi: "7 साल",
    },
    flights: {
      vi: "5000+",
      en: "5000+",
      fr: "5000+",
      ru: "5000+",
      zh: "5000+",
      hi: "5000+",
    },
    hours: {
      vi: "1000+ giờ",
      en: "1000+ hours",
      fr: "1000+ heures",
      ru: "1000+ часов",
      zh: "1000+ 小时",
      hi: "1000+ घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/minh-trung/minh-trung.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/minh-trung/hero-1.png",
      "/pilots/minh-trung/hero-2.png",
      "/pilots/minh-trung/hero-3.png",
      "/pilots/minh-trung/hero-4.png",
      "/pilots/minh-trung/hero-5.png",
      "/pilots/minh-trung/content-1.png",
      "/pilots/minh-trung/content-2.png",
      "/pilots/minh-trung/content-3.png",
    ],
    specialties: {
      vi: ["Bay đường trường", "Video TikTok triệu view"],
      en: ["Cross-country flying", "Million-view TikTok videos"],
      fr: ["Vol de distance (cross)", "Vidéos TikTok à millions de vues"],
      ru: ["Маршрутные полёты (кросс)", "TikTok-видео на миллион просмотров"],
      zh: ["长距离飞行", "百万播放 TikTok 视频"],
      hi: ["क्रॉस-कंट्री उड़ान", "मिलियन-व्यू TikTok वीडियो"],
    },
    certificates: {
      vi: ["Tốt nghiệp An toàn bay tại Nepal"],
      en: ["Graduated Flight Safety training in Nepal"],
      fr: ["Diplômé d’une formation sécurité au Népal"],
      ru: ["Окончил курс по безопасности полётов в Непале"],
      zh: ["毕业于尼泊尔飞行安全培训"],
      hi: ["नेपाल में फ्लाइट सेफ़्टी ट्रेनिंग से स्नातक"],
    },
    bio: {
      vi: "Hơn 5.000 chuyến bay đôi, 7 năm bám dây lơ lửng trên trời, hơn 1.000 giờ “tán mây, thả gió”. Bí danh Trung Chocolate – bay cùng anh, bạn sẽ được chém gió vui hết nấc, cười mỏi miệng!",
      en: "Over 5,000 tandem flights, 7 years in the sky, 1,000+ hours “chatting with clouds and riding the wind”. Alias Trung Chocolate—fly with him and you’ll laugh nonstop!",
      fr: "Plus de 5 000 vols tandem, 7 ans dans le ciel, 1 000+ heures à « discuter avec les nuages ». Surnom Trung Chocolate — avec lui, fous rires garantis !",
      ru: "Более 5 000 тандемных полётов, 7 лет в небе и 1 000+ часов «болтовни с облаками». Псевдоним Trung Chocolate — с ним вы будете смеяться без остановки!",
      zh: "5,000+ 次双人飞行、7 年“挂在天上”、1,000+ 小时“聊云放风”。外号“巧克力Trung”，和他飞就是一路聊天一路笑！",
      hi: "5,000+ टैंडम उड़ानें, 7 साल आसमान में, 1,000+ घंटे ‘बादलों से बातें और हवा के साथ खेल’। उर्फ़ ‘Trung Chocolate’—उनके साथ उड़िए और हँसते-हँसते थक जाएंगे!",
    },
    funFacts: {
      vi: [
        "Cánh dù anh đang bay là cờ đỏ sao vàng rực rỡ — bay là truyền cảm hứng yêu nước, yêu trời, yêu luôn cả cuộc đời.",
        "Bay cùng anh, clip để lên triệu view TikTok, ảnh và video thì “xịn xò” khỏi chỉnh, đủ làm crush cũng phải lỡ nhịp tim.",
        "Tính cách thì hoà đồng, vui vẻ, bảo đảm bạn vừa bay vừa cười toe toét, quên luôn cả sợ độ cao.",
        "Nhược điểm duy nhất? Nắng làm đen da, mưa làm tóc xù — nhưng thần thái vẫn đỉnh, nụ cười thì không chỗ nào chê!",
      ],
      en: [
        "He flies a canopy like Vietnam’s red flag—spreading love for the sky and life.",
        "Fly with him and your clips can hit millions on TikTok—photos/videos are top-notch without edits.",
        "Super sociable and fun—you’ll smile the whole time and forget your fear of heights.",
        "Only downside? Sun tans, rain frizzes hair—still charismatic with a perfect smile!",
      ],
      fr: [
        "Il vole sous une voile comme le drapeau vietnamien—amour du ciel et de la vie.",
        "Avec lui, clips TikTok à millions et photos/vidéos au top, sans retouche.",
        "Très sociable et joyeux—vous oublierez le vertige en souriant.",
        "Seul défaut ? Soleil et pluie… mais charisme et sourire impeccables !",
      ],
      ru: [
        "Летает под куполом как под флагом Вьетнама — вдохновляет любить небо и жизнь.",
        "С ним ваши клипы легко набирают миллионы на TikTok, фото/видео — топ без обработки.",
        "Очень общительный и весёлый — забудете про страх высоты.",
        "Минус один: солнце и дождь… но харизма и улыбка всегда на высоте!",
      ],
      zh: [
        "他飞的伞翼像越南红旗一样醒目——把热爱天空与生活一起带上天。",
        "和他飞，TikTok 轻松冲百万；照片视频不用修也很“高级”。",
        "性格超开朗，保证你边飞边笑，忘掉恐高。",
        "唯一缺点？太阳会晒黑、雨会炸毛——但气场依旧满分，笑容无可挑剔！",
      ],
      hi: [
        "उनका विंग वियतनाम के लाल झंडे जैसा दमदार—उड़ान से देश-प्रेम, आसमान-प्रेम और लाइफ़-लव सब साथ।",
        "उनके साथ उड़ेंगे तो TikTok पर मिलियन-व्यू वाला क्लिप; फोटो/वीडियो बिना एडिट भी शानदार।",
        "बहुत ही फ्रेंडली और मज़ेदार—उड़ते-उड़ते डर भूल जाएंगे।",
        "बस एक कमी? धूप टैन और बारिश बालों को फ्रिज़ कर दे—फिर भी स्टाइल और मुस्कान परफेक्ट!",
      ],
    },
    achievements: {
      vi: [
        "Hơn 5.000 chuyến bay đôi an toàn với hành khách",
        "7 năm kinh nghiệm bay dù lượn, chuyên sâu trong lĩnh vực bay đôi và bay đường trường",
        "Tích lũy hơn 1.000 giờ bay thực tế, làm chủ nhiều điều kiện thời tiết và địa hình phức tạp",
        "Tốt nghiệp khóa huấn luyện An toàn bay tại Nepal, quốc gia có điều kiện bay khắt khe và tiêu chuẩn quốc tế cao",
      ],
      en: [
        "5,000+ safe tandem flights.",
        "7 years of experience, specializing in tandem and cross-country flying.",
        "1,000+ hours of real flight time in complex conditions.",
        "Graduated from Flight Safety training in Nepal.",
      ],
      fr: [
        "5 000+ vols tandem en toute sécurité.",
        "7 ans d'expérience, spécialisé tandem et cross.",
        "1 000+ heures en conditions complexes.",
        "Diplômé d'une formation sécurité au Népal.",
      ],
      ru: [
        "5 000+ безопасных тандемных полётов.",
        "7 лет опыта, специализация тандем и маршрутные полёты.",
        "1 000+ часов налёта в сложных условиях.",
        "Окончил курс по безопасности полётов в Непале.",
      ],
      zh: [
        "5,000+ 次安全双人飞行。",
        "7 年经验，专长双人飞与长距离飞行。",
        "累计 1,000+ 小时实飞，适应多种复杂气象与地形。",
        "毕业于尼泊尔飞行安全培训课程。",
      ],
      hi: [
        "5,000+ सुरक्षित टैंडम उड़ानें।",
        "7 साल का अनुभव—टैंडम और क्रॉस-कंट्री में विशेषज्ञ।",
        "1,000+ घंटे वास्तविक उड़ान समय, जटिल मौसम/टेर्रेन में महारत।",
        "नेपाल में फ्लाइट सेफ़्टी ट्रेनिंग कोर्स से स्नातक।",
      ],
    },
    flyingStyle: {
      vi: "Bay vui hết nấc, clip triệu view, chuyên bay đường trường.",
      en: "Endlessly fun flights, million-view clips, cross-country specialist.",
      fr: "Vols fun, clips à un million de vues, spécialiste du cross.",
      ru: "Весёлые полёты, клипы на миллион, специалист по маршрутным полётам.",
      zh: "飞行氛围拉满、视频出片率高，擅长长距离飞行。",
      hi: "फुल-फन फ्लाइट, मिलियन-व्यू क्लिप्स, क्रॉस-कंट्री स्पेशलिस्ट।",
    },
  },

  {
    slug: "phan-hung",
    name: "PHAN HÙNG",
    nickname: {
      vi: "Lãng khách bầu trời",
      en: "Sky Wanderer",
      fr: "Vagabond du Ciel",
      ru: "Небесный странник",
      zh: "天空旅人",
      hi: "आसमान का यात्री",
    },
    role: {
      vi: "Phi công",
      en: "Pilot",
      fr: "Pilote",
      ru: "Пилот",
      zh: "飞行员",
      hi: "पायलट",
    },
    experience: {
      vi: "Từ 2018",
      en: "Since 2018",
      fr: "Depuis 2018",
      ru: "С 2018 года",
      zh: "自 2018 年起",
      hi: "2018 से",
    },
    flights: {
      vi: "3000+",
      en: "3000+",
      fr: "3000+",
      ru: "3000+",
      zh: "3000+",
      hi: "3000+",
    },
    hours: {
      vi: "Nhiều giờ",
      en: "Many hours",
      fr: "De nombreuses heures",
      ru: "Много часов",
      zh: "许多小时",
      hi: "कई घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/phan-hung/phan-hung.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/phan-hung/hero-1.png",
      "/pilots/phan-hung/hero-2.png",
      "/pilots/phan-hung/hero-3.png",
      "/pilots/phan-hung/hero-4.png",
      "/pilots/phan-hung/hero-5.png",
      "/pilots/phan-hung/content-1.png",
      "/pilots/phan-hung/content-2.png",
      "/pilots/phan-hung/content-3.png",
    ],
    specialties: {
      vi: ["Góc quay nghệ thuật", "Clip triệu view"],
      en: ["Artistic camera angles", "Million-view clips"],
      fr: ["Angles de caméra artistiques", "Clips à millions de vues"],
      ru: ["Художественные ракурсы", "Клипы на миллион просмотров"],
      zh: ["艺术镜头", "百万播放视频"],
      hi: ["आर्टिस्टिक कैमरा एंगल्स", "मिलियन-व्यू क्लिप्स"],
    },
    certificates: {
      vi: ["Huấn luyện chuẩn quốc tế"],
      en: ["International-standard training"],
      fr: ["Formation aux standards internationaux"],
      ru: ["Обучение по международным стандартам"],
      zh: ["国际标准培训"],
      hi: ["इंटरनेशनल-स्टैंडर्ड ट्रेनिंग"],
    },
    bio: {
      vi: "Bay cùng anh, bạn sẽ có clip triệu view triệu like với góc quay siêu nghệ thuật. Trải nghiệm an toàn tuyệt đối và khoảnh khắc bầu trời tuyệt đẹp được lưu giữ, mang về những tư liệu quý giá khó quên trên từng chuyến bay đôi.",
      en: "Fly with him and you’ll get million-view clips with artistic angles. Absolute safety and stunning sky moments captured—precious memories from every tandem flight.",
      fr: "Volez avec lui : clips à un million de vues avec des angles artistiques. Sécurité totale et souvenirs du ciel capturés à chaque vol.",
      ru: "С ним — клипы на миллион просмотров с художественными ракурсами. Максимальная безопасность и прекрасные моменты неба, сохранённые в памяти и кадрах.",
      zh: "和他一起飞，艺术感十足的镜头轻松出“百万播放”。安全感拉满，把最美的天空瞬间都帮你记录下来。",
      hi: "उनके साथ उड़ेंगे तो सुपर-आर्टिस्टिक एंगल्स के साथ मिलियन-व्यू क्लिप्स मिलेंगे। पूरी सुरक्षा के साथ आसमान के खूबसूरत पलों को यादगार रूप में कैप्चर किया जाएगा।",
    },
    funFacts: {
      vi: [
        "Gặp Phan Hùng – “rocker” của bầu trời, tóc dài bay trong gió như chính đôi cánh dù lượn.",
        "Bay cùng anh, bạn không chỉ có clip triệu view mà còn triệu cảm xúc.",
        "Hơn 1000 chuyến bay – mỗi chuyến là một câu chuyện, là khoảnh khắc để đời.",
        "Giàu năng lượng, am hiểu địa hình, đam mê “cháy” – sẵn sàng đưa bạn chạm mây!",
      ],
      en: [
        "Meet Phan Hung—the sky’s ‘rocker’, long hair flowing like a wing in the wind.",
        "With him you get not only million-view clips but also a million emotions.",
        "3000+ flights—each one a story and a lifetime memory.",
        "High energy, terrain-savvy, burning passion—ready to take you to the clouds!",
      ],
      fr: [
        "Phan Hung, le 'rockeur' du ciel : cheveux au vent comme une aile.",
        "Avec lui : clips à un million de vues et un million d'émotions.",
        "3000+ vols — chaque vol est une histoire et un souvenir.",
        "Énergie, connaissance du terrain, passion — prêt à vous faire toucher les nuages !",
      ],
      ru: [
        "Фан Хунг — «рокер» неба: длинные волосы развеваются, как крыло.",
        "С ним — не только клипы на миллион, но и миллион эмоций.",
        "3000+ полётов — каждый полёт как история на всю жизнь.",
        "Энергичный, отлично знает местность и «горит» делом — готов поднять вас к облакам!",
      ],
      zh: [
        "天空“摇滚客”——长发随风飘，像伞翼一样帅。",
        "和他飞，不只是百万播放的片子，还有“百万情绪”。",
        "3000+ 次飞行——每次都是故事、都是一生的记忆。",
        "能量满格、地形熟、热情燃——随时带你触碰云层！",
      ],
      hi: [
        "Phan Hùng—आसमान के ‘रॉकर’; लंबे बाल हवा में विंग की तरह लहराते।",
        "उनके साथ सिर्फ मिलियन-व्यू क्लिप ही नहीं, मिलियन इमोशन्स भी।",
        "3000+ उड़ानें—हर उड़ान एक कहानी, एक लाइफटाइम मोमेंट।",
        "हाई-एनर्जी, टेर्रेन की शानदार समझ, और जबरदस्त पैशन—आपको बादलों तक ले जाने को तैयार!",
      ],
    },
    achievements: {
      vi: [
        "Phan Hùng bắt đầu theo đuổi đam mê dù lượn từ năm 2018 và đã có nhiều năm kinh nghiệm bay chuyên nghiệp tại Việt Nam.",
        "Anh am hiểu sâu sắc về khí tượng và địa hình tại các điểm bay trên khắp cả nước, là yếu tố quan trọng đảm bảo mỗi chuyến bay đều an toàn và tối ưu trải nghiệm.",
        "Đã thực hiện hơn 3000 chuyến bay đôi chuyên nghiệp tại Việt Nam",
        "Liên tục tham gia các khoá học đào tạo, huấn luyện theo chuẩn quốc tế về dù lượn",
      ],
      en: [
        "Started paragliding in 2018 and gained years of professional experience in Vietnam.",
        "Deep understanding of meteorology and terrain nationwide, ensuring safe & optimal flights.",
        "Completed 3000+ professional tandem flights in Vietnam.",
        "Continuously joins international-standard training courses.",
      ],
      fr: [
        "A commencé en 2018 et a accumulé une solide expérience professionnelle au Vietnam.",
        "Excellente compréhension météo/terrain pour garantir sécurité et optimisation.",
        "3000+ vols tandem professionnels au Vietnam.",
        "Suit régulièrement des formations aux standards internationaux.",
      ],
      ru: [
        "Начал заниматься в 2018 году и накопил многолетний профессиональный опыт во Вьетнаме.",
        "Глубоко разбирается в метеоусловиях и рельефе по стране, обеспечивая безопасность и лучший опыт.",
        "3000+ профессиональных тандемных полётов во Вьетнаме.",
        "Регулярно проходит обучение по международным стандартам.",
      ],
      zh: [
        "自 2018 年开始投入滑翔伞，拥有多年越南专业飞行经验。",
        "深入理解全国各飞行点的气象与地形，保障安全并优化体验。",
        "在越南完成 3000+ 次专业双人飞行。",
        "持续参加国际标准的培训与进阶课程。",
      ],
      hi: [
        "2018 से पैराग्लाइडिंग में सक्रिय—वियतनाम में कई वर्षों का प्रोफेशनल अनुभव।",
        "देशभर के मौसम/टेर्रेन की गहरी समझ—सुरक्षित और बेहतरीन अनुभव सुनिश्चित।",
        "वियतनाम में 3000+ प्रोफेशनल टैंडम उड़ानें।",
        "लगातार इंटरनेशनल-स्टैंडर्ड ट्रेनिंग/कोर्सेज़ में भागीदारी।",
      ],
    },
    flyingStyle: {
      vi: "Góc quay siêu nghệ thuật, clip triệu view, trải nghiệm an toàn tuyệt đối.",
      en: "Artistic camera angles, million-view clips, absolutely safe experience.",
      fr: "Angles artistiques, clips à million de vues, sécurité totale.",
      ru: "Художественные ракурсы, клипы на миллион, максимальная безопасность.",
      zh: "镜头感强、出片率高，飞行安全稳妥。",
      hi: "सुपर-आर्टिस्टिक एंगल्स, मिलियन-व्यू क्लिप्स, पूरी सुरक्षा के साथ।",
    },
  },

  {
    slug: "ngo-doi",
    name: "NGÔ VĂN ĐỘI",
    nickname: {
      vi: "Chiến binh lượn lách",
      en: "Maneuver Warrior",
      fr: "Guerrier de la Manœuvre",
      ru: "Воин манёвров",
      zh: "机动战士",
      hi: "मैनूवर वॉरियर",
    },
    role: {
      vi: "Phi công",
      en: "Pilot",
      fr: "Pilote",
      ru: "Пилот",
      zh: "飞行员",
      hi: "पायलट",
    },
    experience: {
      vi: "5 năm",
      en: "5 years",
      fr: "5 ans",
      ru: "5 лет",
      zh: "5 年",
      hi: "5 साल",
    },
    flights: {
      vi: "1500+",
      en: "1500+",
      fr: "1500+",
      ru: "1500+",
      zh: "1500+",
      hi: "1500+",
    },
    hours: {
      vi: "500+ giờ",
      en: "500+ hours",
      fr: "500+ heures",
      ru: "500+ часов",
      zh: "500+ 小时",
      hi: "500+ घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/ngo-doi/ngo-doi.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/ngo-doi/hero-1.png",
      "/pilots/ngo-doi/hero-2.png",
      "/pilots/ngo-doi/hero-3.png",
      "/pilots/ngo-doi/hero-4.png",
      "/pilots/ngo-doi/hero-5.png",
      "/pilots/ngo-doi/content-1.png",
      "/pilots/ngo-doi/content-2.png",
      "/pilots/ngo-doi/content-3.png",
    ],
    specialties: {
      vi: ["Bay phấn khích", "Vui vẻ", "An toàn"],
      en: ["Exciting flights", "Fun", "Safety"],
      fr: ["Vols excitants", "Fun", "Sécurité"],
      ru: ["Драйвовые полёты", "Весело", "Безопасность"],
      zh: ["刺激飞行", "氛围开心", "安全"],
      hi: ["रोमांचक फ्लाइट", "मज़ेदार", "सेफ़्टी"],
    },
    certificates: {
      vi: ["Kỷ lục bay 7 giờ liên tục tại Đồi Bù"],
      en: ["7-hour continuous flight record at Doi Bu"],
      fr: ["Record de 7h de vol continu à Doi Bu"],
      ru: ["Рекорд 7 часов непрерывного полёта в Дой Бу"],
      zh: ["Đồi Bù 连飞 7 小时纪录"],
      hi: ["Đồi Bù पर 7 घंटे लगातार उड़ान रिकॉर्ड"],
    },
    bio: {
      vi: "Tham gia mọi giải đấu dù lượn tại Việt Nam, giữ kỷ lục 7 giờ bay liên tục tại Đồi Bù – Chương Mỹ. Anh đam mê dù lượn, mang đến cho khách hàng trải nghiệm bay đầy phấn khích, an toàn và ngập tràn tiếng cười.",
      en: "Competes across Vietnam and holds a 7-hour continuous flight record at Doi Bu – Chuong My. Passionate and fun, he delivers exciting yet safe flights full of laughter.",
      fr: "Participe aux compétitions au Vietnam et détient un record de 7h de vol continu à Doi Bu – Chuong My. Passionné, il offre des vols excitants et sûrs, pleins de rires.",
      ru: "Участвует во всех соревнованиях во Вьетнаме и держит рекорд 7 часов непрерывного полёта в Дой Бу – Чыонг Ми. Дарит драйв, безопасность и море смеха.",
      zh: "参加越南各类赛事，并保持“Đồi Bù 连飞 7 小时”纪录。热爱飞行、氛围感超强，带来刺激又安全、笑声不断的体验。",
      hi: "वियतनाम की कई प्रतियोगिताओं में भाग लेते हैं और Đồi Bù पर 7 घंटे लगातार उड़ान का रिकॉर्ड रखते हैं। जोश, सुरक्षा और हँसी—सब एक साथ!",
    },
    funFacts: {
      vi: [
        "Chàng trai trẻ mang gió vào… nụ cười, bay cao chẳng cần “đi thang máy”!",
        "Đam mê dù lượn cháy bỏng — mỗi chuyến bay là một trái tim “cất cánh”",
        "Bay cùng anh, bạn sẽ cảm nhận niềm vui trên cao — gió lùa mạnh như đang vỗ tay cổ vũ bạn.",
        "Người bạn đồng hành siêu tận tâm, sẵn sàng biến giấc mơ bay lơ lửng thành chuyến phiêu lưu kỳ thú",
      ],
      en: [
        "A young guy who brings the wind into his smile—no 'elevator' needed to fly high!",
        "Burning passion—every flight is a heart taking off.",
        "Up there you’ll feel pure joy—the wind cheers for you.",
        "Super dedicated companion, turning your floating dream into an adventure.",
      ],
      fr: [
        "Un jeune homme au sourire plein de vent—pas besoin d'ascenseur pour monter !",
        "Passion brûlante—chaque vol fait décoller le cœur.",
        "En altitude, la joie est totale—le vent vous applaudit.",
        "Compagnon dévoué, il transforme votre rêve en aventure.",
      ],
      ru: [
        "Молодой парень с ветром в улыбке — взлетает без «лифта»!",
        "Горит парапланеризмом — каждый полёт как взлёт сердца.",
        "С ним наверху — сплошная радость, ветер будто аплодирует.",
        "Очень внимательный напарник: превратит мечту о полёте в классное приключение.",
      ],
      zh: [
        "把风带进笑容的年轻人——飞上天不需要“电梯”！",
        "热爱到发光——每次飞行都是“心动起飞”。",
        "和他一起飞，你会感到高空的快乐，风像在为你鼓掌。",
        "超负责的同伴，把“漂浮的梦想”变成精彩冒险。",
      ],
      hi: [
        "ऐसा युवा जो अपनी मुस्कान में हवा भर देता है—ऊँचा उड़ने के लिए ‘लिफ्ट’ की ज़रूरत नहीं!",
        "जलता हुआ पैशन—हर उड़ान एक ‘टेक-ऑफ’ करता दिल।",
        "उनके साथ ऊपर खुशी अलग ही—हवा जैसे तालियाँ बजा रही हो।",
        "बहुत डेडिकेटेड साथी—आपके उड़ान-सपने को रोमांचक एडवेंचर बना देंगे।",
      ],
    },
    achievements: {
      vi: [
        "Từ năm 2023 đến 2025, anh đã thực hiện hơn 1500 chuyến bay đơn và bay đôi tại hầu hết các điểm bay nổi tiếng trên khắp Việt Nam.",
        "Tích lũy hơn 500 giờ bay thực tế, cùng với 5 năm kinh nghiệm vững chắc trong lĩnh vực dù lượn.",
        "Gương mặt quen thuộc tại tất cả các giải đấu dù lượn từ Nam ra Bắc, luôn góp mặt với tinh thần thi đấu chuyên nghiệp và niềm đam mê mạnh liệt.",
        "Lập kỷ lục bay liên tục 7 tiếng tại Chương Mỹ – Đồi Bù, đánh dấu một cột mốc quan trọng trong sự nghiệp bay của mình.",
      ],
      en: [
        "2023–2025: 1500+ solo & tandem flights at top spots across Vietnam.",
        "500+ real flight hours with 5 years of experience.",
        "A familiar competitor nationwide with strong passion and professionalism.",
        "Set a 7-hour continuous flight record at Chuong My – Doi Bu.",
      ],
      fr: [
        "2023–2025 : 1500+ vols solo et tandem sur les meilleurs sites au Vietnam.",
        "500+ heures de vol, 5 ans d'expérience.",
        "Présent sur les compétitions du Nord au Sud.",
        "Record de 7h de vol continu à Chuong My – Doi Bu.",
      ],
      ru: [
        "2023–2025: 1500+ одиночных и тандемных полётов по Вьетнаму.",
        "500+ часов налёта и 5 лет опыта.",
        "Постоянный участник соревнований по всей стране.",
        "Рекорд 7 часов непрерывного полёта в Чыонг Ми – Дой Бу.",
      ],
      zh: [
        "2023–2025：在越南各大热门点完成 1500+ 次单飞/双人飞行。",
        "累计 500+ 小时实飞，拥有 5 年扎实经验。",
        "全国赛事常客，专业且充满热情。",
        "在 Chương Mỹ – Đồi Bù 创下连续飞行 7 小时纪录。",
      ],
      hi: [
        "2023–2025: वियतनाम के प्रमुख स्पॉट्स पर 1500+ सोलो/टैंडम उड़ानें।",
        "500+ वास्तविक उड़ान घंटे और 5 साल का मजबूत अनुभव।",
        "नॉर्थ-टू-साउथ प्रतियोगिताओं में नियमित भागीदारी।",
        "Chương Mỹ – Đồi Bù पर 7 घंटे लगातार उड़ान का रिकॉर्ड।",
      ],
    },
    flyingStyle: {
      vi: "Trải nghiệm bay đầy phấn khích, an toàn và ngập tràn tiếng cười.",
      en: "Exciting, safe, and full of laughter.",
      fr: "Excitant, sûr et plein de rires.",
      ru: "Драйвово, безопасно и очень весело.",
      zh: "刺激但稳，安全拉满，笑声不断。",
      hi: "रोमांचक लेकिन सुरक्षित—और हँसी से भरपूर।",
    },
  },

  {
    slug: "minh-vo",
    name: "MINH VÕ",
    nickname: {
      vi: "Đại bàng thép",
      en: "Steel Eagle",
      fr: "Aigle d'Acier",
      ru: "Стальной орёл",
      zh: "钢铁雄鹰",
      hi: "स्टील ईगल",
    },
    role: {
      vi: "Phi công",
      en: "Pilot",
      fr: "Pilote",
      ru: "Пилот",
      zh: "飞行员",
      hi: "पायलट",
    },
    experience: {
      vi: "14 năm",
      en: "14 years",
      fr: "14 ans",
      ru: "14 лет",
      zh: "14 年",
      hi: "14 साल",
    },
    flights: {
      vi: "5000+",
      en: "5000+",
      fr: "5000+",
      ru: "5000+",
      zh: "5000+",
      hi: "5000+",
    },
    hours: {
      vi: "Nhiều giờ",
      en: "Many hours",
      fr: "De nombreuses heures",
      ru: "Много часов",
      zh: "许多小时",
      hi: "कई घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/minh-vo/minh-vo.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/minh-vo/hero-1.png",
      "/pilots/minh-vo/hero-2.png",
      "/pilots/minh-vo/hero-3.png",
      "/pilots/minh-vo/hero-4.png",
      "/pilots/minh-vo/hero-5.png",
      "/pilots/minh-vo/content-1.png",
      "/pilots/minh-vo/content-2.png",
      "/pilots/minh-vo/content-3.png",
    ],
    specialties: {
      vi: ["Phi công kỳ cựu", "Truyền lửa đam mê"],
      en: ["Veteran pilot", "Passion igniter"],
      fr: ["Pilote vétéran", "Transmet la passion"],
      ru: ["Опытный пилот", "Зажигает страсть"],
      zh: ["资深飞行员", "点燃热情"],
      hi: ["वेटरन पायलट", "पैशन जगाने वाले"],
    },
    certificates: {
      vi: ["Top 5 phi công đời đầu", "Giải Nhất Hạ Cánh Chính Xác MCC 2023"],
      en: ["Top 5 first-generation pilots", "1st Prize Precision Landing (MCC 2023)"],
      fr: ["Top 5 de la première génération", "1er prix Atterrissage de précision (MCC 2023)"],
      ru: ["Топ-5 пилотов первого поколения", "1-е место: точность приземления (MCC 2023)"],
      zh: ["第一代飞行员 Top 5", "MCC 2023 精准降落冠军"],
      hi: ["पहली पीढ़ी के Top 5 पायलट", "MCC 2023 प्रिसिजन लैंडिंग 1st प्राइज़"],
    },
    bio: {
      vi: "Bay cùng “phi công triệu like” với 14 năm kinh nghiệm. Đam mê bầu trời từ nhỏ, anh truyền lửa qua từng chuyến bay đôi, mang đến trải nghiệm tuyệt đỉnh và khoảnh khắc đáng nhớ cho mọi khách hàng.",
      en: "Fly with the 'million-like pilot' with 14 years of experience. Passionate about the sky since childhood, he spreads enthusiasm through every tandem flight, delivering supreme experiences and memorable moments.",
      fr: "Volez avec le « pilote au million de likes » (14 ans d'expérience). Passionné depuis l'enfance, il transmet sa flamme à chaque vol tandem.",
      ru: "Летайте с «пилотом на миллион лайков» (14 лет опыта). С детства влюблён в небо, он дарит яркие эмоции и незабываемые моменты на каждом тандемном полёте.",
      zh: "与“百万点赞飞行员”一起飞——14 年经验，从小热爱天空，把热情与安全感带进每一次双人飞行。",
      hi: "‘मिलियन-लाइक पायलट’ के साथ उड़िए—14 साल का अनुभव। बचपन से आसमान के दीवाने, हर टैंडम फ्लाइट में जोश और यादगार पल देते हैं।",
    },
    funFacts: {
      vi: [
        "Minh Võ – “phi công triệu like” với niềm đam mê bầu trời từ bé, lớn lên chỉ thích trò chuyện với mây và chơi đùa với gió. Bay cùng anh không chỉ là lên cao, mà còn lên tâm trạng, view đẹp, và tiếng cười rộn ràng suốt chuyến đi. Anh truyền lửa như tênh mà chất lừ, khiến bay xong cũng chỉ muốn… bay thêm lần nữa cho đã!",
      ],
      en: [
        "Minh Vo—the 'million-like pilot' who loves chatting with clouds and playing with the wind. Flying with him means great vibes, beautiful views, and laughter all the way—after landing you’ll want another flight!",
      ],
      fr: [
        "Minh Vo — le « pilote au million de likes ». Avec lui : bonne humeur, vues splendides et rires. Après l’atterrissage, vous voudrez repartir !",
      ],
      ru: [
        "Минь Во — «пилот на миллион лайков». Обожает облака и ветер. С ним — отличное настроение, красивые виды и смех, а после посадки хочется лететь ещё!",
      ],
      zh: [
        "Minh Võ 是“百万点赞飞行员”，从小就爱和云聊天、和风玩耍。和他飞不只是上天，更是心情起飞：风景漂亮、一路欢笑，落地还想再飞一趟！",
      ],
      hi: [
        "Minh Võ—‘मिलियन-लाइक पायलट’। बादलों से बातें और हवा के साथ खेलना उनका स्टाइल है। उनके साथ उड़ान = शानदार मूड, खूबसूरत व्यू और ढेर सारी हँसी—लैंडिंग के बाद फिर उड़ने का मन करेगा!",
      ],
    },
    achievements: {
      vi: [
        "Với 14 năm kinh nghiệm bay dù lượn và hơn 2.000 chuyến bay đôi an toàn, anh là một trong những phi công kỳ cựu và đáng tin cậy hàng đầu tại Việt Nam.",
        "Là một trong Top 5 phi công đời đầu, anh đã góp phần đặt nền móng cho cộng đồng dù lượn trong nước.",
        "Năm 2023, anh cùng đồng đội xuất sắc giành giải Nhất nội dung Hạ Cánh Chính Xác tại giải đấu MCC, khẳng định kỹ năng chuyên môn và bản lĩnh thi đấu vững vàng.",
      ],
      en: [
        "14 years of experience and 5,000+ safe tandem flights—one of Vietnam’s most reliable veteran pilots.",
        "Top 5 first-generation pilots—helped build the local paragliding community.",
        "Won 1st prize in Precision Landing at MCC 2023 with his team.",
      ],
      fr: [
        "14 ans d'expérience et 5 000+ vols tandem sûrs—un vétéran fiable au Vietnam.",
        "Top 5 de la première génération—acteur fondateur de la communauté.",
        "1er prix Atterrissage de précision au MCC 2023 (avec l’équipe).",
      ],
      ru: [
        "14 лет опыта и 5 000+ безопасных тандемных полётов — один из самых надёжных пилотов-ветеранов Вьетнама.",
        "Топ-5 пилотов первого поколения — помогал развивать сообщество.",
        "1-е место в дисциплине «Точность приземления» на MCC 2023 (в команде).",
      ],
      zh: [
        "14 年经验、5,000+ 次安全双人飞行——越南最可靠的资深飞行员之一。",
        "“第一代飞行员”Top 5，参与奠定本土滑翔伞社群基础。",
        "2023 年 MCC 比赛精准降落项目与队友夺得冠军。",
      ],
      hi: [
        "14 साल का अनुभव और 5,000+ सुरक्षित टैंडम उड़ानें—वियतनाम के भरोसेमंद वेटरन पायलट्स में से एक।",
        "पहली पीढ़ी के Top 5 पायलट—लोकल पैराग्लाइडिंग कम्युनिटी की नींव में योगदान।",
        "MCC 2023 में प्रिसिजन लैंडिंग में टीम के साथ 1st प्राइज़।",
      ],
    },
    flyingStyle: {
      vi: "Phi công kỳ cựu, truyền lửa đam mê, mang đến trải nghiệm tuyệt đỉnh.",
      en: "Veteran pilot who spreads passion and delivers a supreme experience.",
      fr: "Pilote vétéran, transmet la passion, offre une expérience au top.",
      ru: "Опытный пилот, заряжает страстью и дарит лучший опыт.",
      zh: "资深稳健、感染力强，把安全与体验做得非常到位。",
      hi: "वेटरन पायलट—पैशन भी, परफेक्ट एक्सपीरियंस भी।",
    },
  },

  {
    slug: "toan-nguyen",
    name: "TOÀN NGUYỄN",
    nickname: {
      vi: "Rambo",
      en: "Rambo",
      fr: "Rambo",
      ru: "Рэмбо",
      zh: "兰博",
      hi: "रैम्बो",
    },
    role: {
      vi: "Phi công",
      en: "Pilot",
      fr: "Pilote",
      ru: "Пилот",
      zh: "飞行员",
      hi: "पायलट",
    },
    experience: {
      vi: "10+ năm",
      en: "10+ years",
      fr: "10+ ans",
      ru: "10+ лет",
      zh: "10+ 年",
      hi: "10+ साल",
    },
    flights: {
      vi: "5000-",
      en: "5000-",
      fr: "5000-",
      ru: "5000-",
      zh: "5000-",
      hi: "5000-",
    },
    hours: {
      vi: "Nhiều giờ",
      en: "Many hours",
      fr: "De nombreuses heures",
      ru: "Много часов",
      zh: "许多小时",
      hi: "कई घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/toan-nguyen/toan-nguyen.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/toan-nguyen/hero-1.png",
      "/pilots/toan-nguyen/hero-2.png",
      "/pilots/toan-nguyen/hero-3.png",
      "/pilots/toan-nguyen/hero-4.png",
      "/pilots/toan-nguyen/hero-5.png",
      "/pilots/toan-nguyen/content-1.png",
      "/pilots/toan-nguyen/content-2.png",
      "/pilots/toan-nguyen/content-3.png",
    ],
    specialties: {
      vi: ["Bay nhiều điểm", "Vui vẻ"],
      en: ["Multi-spot flying", "Fun"],
      fr: ["Vol sur plusieurs sites", "Fun"],
      ru: ["Полёты по разным локациям", "Весело"],
      zh: ["多点飞行", "氛围开心"],
      hi: ["कई स्पॉट्स पर उड़ान", "मज़ेदार"],
    },
    certificates: {
      vi: ["Tốt nghiệp an toàn bay chuẩn quốc tế"],
      en: ["Graduated international-standard flight safety training"],
      fr: ["Diplômé d’une formation sécurité aux normes internationales"],
      ru: ["Окончил обучение по безопасности полётов по международным стандартам"],
      zh: ["完成国际标准飞行安全培训"],
      hi: ["इंटरनेशनल-स्टैंडर्ड फ्लाइट सेफ़्टी ट्रेनिंग से स्नातक"],
    },
    bio: {
      vi: "Hơn 10 năm cày gió cưỡi mây, gần 5000 chuyến bay. Bay khắp Việt Nam: Kon Tum, Lý Sơn, Điện Biên.. GPS còn chưa kịp load, anh đã đặt chân tới! Dù lượn với anh không chỉ là đam mê – là phong cách sống trên mây.",
      en: "Over 10 years riding wind and clouds, nearly 5,000 flights. Flew all over Vietnam—Kon Tum, Ly Son, Dien Bien... Before GPS loads, he’s already there! Paragliding is his lifestyle in the clouds.",
      fr: "Plus de 10 ans à chevaucher le vent, près de 5 000 vols. Partout au Vietnam : Kon Tum, Ly Son, Dien Bien... Avant que le GPS charge, il y est déjà !",
      ru: "Более 10 лет с ветром и облаками, почти 5 000 полётов. Летал по всему Вьетнаму: Контум, Лишон, Дьенбьен… GPS не успевает загрузиться — а он уже там!",
      zh: "10+ 年追风逐云、接近 5,000 次飞行。飞遍越南：昆嵩、李山、奠边……GPS 还没加载完，他已经到位！滑翔伞对他是“云端生活方式”。",
      hi: "10+ साल हवा-बादलों के साथ, करीब 5,000 उड़ानें। वियतनाम भर में—Kon Tum, Lý Sơn, Điện Biên… GPS लोड होने से पहले ही वो पहुँच जाते हैं! पैराग्लाइडिंग उनके लिए ‘क्लाउड-लाइफ़स्टाइल’ है।",
    },
    funFacts: {
      vi: [
        "Bay cùng Toàn Nguyễn – “Rambo” trên trời, bạn không chỉ được “cưỡi mây” mà còn được… cười mỏi miệng!",
        "Anh ấy bay như gió, nói như gió, mang lại cảm giác vừa an toàn vừa vui không tưởng. Bay xong chắc chắn bạn sẽ muốn gọi anh ấy làm “phi công ruột” cho mọi chuyến đi. Đảm bảo một điều: lên cùng Toàn, xuống không muốn rời!",
      ],
      en: [
        "Fly with Toan Nguyen—‘Rambo’ in the sky: ride the clouds and laugh nonstop!",
        "He flies like the wind and talks like the wind—safe and insanely fun. After one flight, you’ll want him as your go-to pilot. Guaranteed: you won’t want to leave after landing!",
      ],
      fr: [
        "Volez avec Toan Nguyen—le « Rambo » du ciel : ride des nuages et fous rires !",
        "Il vole et parle comme le vent : sûr et ultra fun. Après un vol, vous le voudrez comme pilote attitré !",
      ],
      ru: [
        "С Тоаном — «Рэмбо» неба: покатаетесь на облаках и насмеётесь!",
        "Летает и говорит как ветер — безопасно и очень весело. После полёта захотите его «своим» пилотом. Гарантия: после посадки не захочется уходить!",
      ],
      zh: [
        "和 Toàn 一起飞——天空中的“兰博”：不仅是“骑云”，还会笑到嘴酸！",
        "他飞得像风、说话也像风：安全又超有趣。飞完你一定想把他当作“固定飞行员”。保证：上去了就不想下来！",
      ],
      hi: [
        "Toàn Nguyễn के साथ उड़िए—आसमान का ‘रैम्बो’: बादलों की सवारी और हँसी की बारिश!",
        "वो हवा की तरह उड़ते और बोलते हैं—सेफ़ भी, सुपर-फन भी। एक बार उड़ेंगे तो उन्हें हर ट्रिप का ‘गो-टू पायलट’ बनाना चाहेंगे। गारंटी: लैंडिंग के बाद भी छोड़ने का मन नहीं करेगा!",
      ],
    },
    achievements: {
      vi: [
        "Với hơn 10 năm kinh nghiệm chinh phục bầu trời, gần 5.000 chuyến bay đơn và đôi, anh là một trong những phi công giàu trải nghiệm và đáng tin cậy tại Việt Nam.",
        "Tốt nghiệp khóa huấn luyện an toàn bay đạt tiêu chuẩn quốc tế",
        "Đã từng bay qua hầu hết các điểm dù lượn nổi tiếng tại Việt Nam như Kon Tum, Đắk Nông, Nha Trang, Lý Sơn, Điện Biên Phủ",
        "Thường xuyên tham gia các giải thi đấu hạ cánh chính xác tại các địa danh như Hà Nội, Mù Cang Chải, Đà Nẵng, khẳng định kỹ năng và bản lĩnh thi đấu ổn định.",
      ],
      en: [
        "10+ years of experience, nearly 5,000 solo & tandem flights—highly reliable in Vietnam.",
        "Graduated from international-standard flight safety training.",
        "Flew at most famous Vietnam spots: Kon Tum, Dak Nong, Nha Trang, Ly Son, Dien Bien Phu.",
        "Regular precision landing competitor: Hanoi, Mu Cang Chai, Da Nang...",
      ],
      fr: [
        "10+ ans d'expérience, près de 5 000 vols—pilote fiable au Vietnam.",
        "Diplômé d'une formation sécurité aux normes internationales.",
        "A volé sur la plupart des sites célèbres : Kon Tum, Dak Nong, Nha Trang, Ly Son, Dien Bien Phu.",
        "Participe régulièrement aux compétitions d'atterrissage de précision.",
      ],
      ru: [
        "10+ лет опыта и почти 5 000 полётов — один из самых опытных и надёжных пилотов.",
        "Окончил обучение по безопасности полётов по международным стандартам.",
        "Летал на самых известных точках Вьетнама: Контум, Дакнонг, Нячанг, Лишон, Дьенбьенфу.",
        "Регулярно участвует в соревнованиях по точности приземления.",
      ],
      zh: [
        "10+ 年经验，接近 5,000 次单飞/双人飞行，是越南非常可靠的飞行员之一。",
        "完成国际标准飞行安全培训。",
        "飞遍越南热门点：昆嵩、得农、芽庄、李山、奠边府等。",
        "常参加精准降落赛事（河内、Mù Cang Chải、岘港等），技能稳定。",
      ],
      hi: [
        "10+ साल का अनुभव, लगभग 5,000 सोलो/टैंडम उड़ानें—वियतनाम के सबसे भरोसेमंद पायलट्स में से एक।",
        "इंटरनेशनल-स्टैंडर्ड फ्लाइट सेफ़्टी ट्रेनिंग से स्नातक।",
        "Kon Tum, Đắk Nông, Nha Trang, Lý Sơn, Điện Biên Phủ सहित कई प्रसिद्ध स्पॉट्स पर उड़ान।",
        "Hanoi, Mù Cang Chải, Đà Nẵng आदि में प्रिसिजन लैंडिंग प्रतियोगिताओं में नियमित भागीदारी।",
      ],
    },
    flyingStyle: {
      vi: "Phong cách sống trên mây, bay như gió, nói như gió, an toàn và vui không tưởng.",
      en: "A cloud lifestyle—flies and talks like the wind; safe and incredibly fun.",
      fr: "Un style de vie dans les nuages : vole et parle comme le vent; sûr et ultra fun.",
      ru: "Жизнь в облаках: летает и говорит как ветер; безопасно и очень весело.",
      zh: "云端生活方式：飞得像风、聊得像风，安全又好玩。",
      hi: "क्लाउड-लाइफ़स्टाइल—हवा की तरह उड़ान/बातें; सेफ़ और जबरदस्त मज़ा।",
    },
  },

  {
    slug: "chien-thang",
    name: "CHIẾN THẮNG",
    nickname: {
      vi: "Thắng thần sét",
      en: "Lightning Victor",
      fr: "Victor Foudroyant",
      ru: "Победитель-молния",
      zh: "雷霆胜者",
      hi: "लाइटनिंग विक्टर",
    },
    role: {
      vi: "Phi công PG & PPG",
      en: "Paragliding & Powered Paragliding Pilot",
      fr: "Pilote parapente & paramoteur",
      ru: "Пилот параплана и парамотора",
      zh: "滑翔伞/动力伞飞行员",
      hi: "पैराग्लाइडिंग व पावर्ड पैराग्लाइडिंग पायलट",
    },
    experience: {
      vi: "7 năm",
      en: "7 years",
      fr: "7 ans",
      ru: "7 лет",
      zh: "7 年",
      hi: "7 साल",
    },
    flights: {
      vi: "4000+",
      en: "4000+",
      fr: "4000+",
      ru: "4000+",
      zh: "4000+",
      hi: "4000+",
    },
    hours: {
      vi: "1000+ giờ",
      en: "1000+ hours",
      fr: "1000+ heures",
      ru: "1000+ часов",
      zh: "1000+ 小时",
      hi: "1000+ घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/chien-thang/chien-thang.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/chien-thang/hero-1.png",
      "/pilots/chien-thang/hero-2.png",
      "/pilots/chien-thang/hero-3.png",
      "/pilots/chien-thang/hero-4.png",
      "/pilots/chien-thang/hero-5.png",
      "/pilots/chien-thang/content-1.png",
      "/pilots/chien-thang/content-2.png",
      "/pilots/chien-thang/content-3.png",
    ],
    specialties: {
      vi: ["Bay an toàn", "Vui vẻ"],
      en: ["Safe flying", "Fun"],
      fr: ["Vol en sécurité", "Fun"],
      ru: ["Безопасный полёт", "Весело"],
      zh: ["安全飞行", "氛围开心"],
      hi: ["सेफ़ फ्लाइंग", "मज़ेदार"],
    },
    certificates: {
      vi: ["Kỷ lục Việt Nam #2 bay đơn 9.5 tiếng"],
      en: ["Vietnam record #2: 9.5-hour solo flight"],
      fr: ["Record Vietnam #2 : vol solo de 9h30"],
      ru: ["Рекорд Вьетнама #2: одиночный полёт 9,5 часов"],
      zh: ["越南纪录第 2：单飞 9.5 小时"],
      hi: ["वियतनाम #2 रिकॉर्ड: 9.5 घंटे सोलो उड़ान"],
    },
    bio: {
      vi: "Anh có 7 năm sống cùng mây gió, hơn 4.000 chuyến bay đôi an toàn, 1.000+ giờ lơ lửng trên trời. Anh từng giữ kỷ lục bay đơn 9 tiếng rưỡi tại Việt Nam! “Càn quét” các giải đấu dù lượn từ Bắc chí Nam, phong độ luôn ở đỉnh cao.",
      en: "7 years with clouds and wind, 4,000+ safe tandem flights, 1,000+ hours in the sky. Once held Vietnam’s 9.5-hour solo flight record! Dominates competitions nationwide.",
      fr: "7 ans avec les nuages et le vent, 4 000+ vols tandem sûrs, 1 000+ heures dans le ciel. A déjà détenu un record de vol solo de 9h30 au Vietnam !",
      ru: "7 лет с облаками и ветром, 4 000+ безопасных тандемных полётов и 1 000+ часов в небе. Устанавливал рекорд Вьетнама по одиночному полёту 9,5 часов!",
      zh: "7 年“云与风的生活”，4,000+ 次安全双人飞行，1,000+ 小时在天空。曾创下越南 9.5 小时单飞纪录！全国赛事表现常年顶尖。",
      hi: "7 साल बादलों-हवा के साथ, 4,000+ सुरक्षित टैंडम उड़ानें, 1,000+ घंटे आसमान में। वियतनाम में 9.5 घंटे सोलो उड़ान रिकॉर्ड भी रहा! पूरे देश की प्रतियोगिताओं में टॉप-फॉर्म।",
    },
    funFacts: {
      vi: [
        "Chiến Thắng – “Thắng thần sét”, bay nhanh như tia chớp mà vẫn khiến bạn yên tâm tuyệt đối.",
        "Lơ lửng trên trời cùng anh, bạn sẽ cười tít mắt vì vui nhưng vẫn muốn xuống.",
        "Bay với anh không chỉ là trải nghiệm mà còn là chuyến phiêu lưu tràn ngập tiếng cười.",
        "Bay lâu đến mức mây cũng phải than phục: “Này, anh còn không thấy à?”",
      ],
      en: [
        "‘Lightning Victor’—fast like lightning but always reassuring.",
        "You’ll grin with joy up there!",
        "Not just a flight—an adventure full of laughter.",
        "Flies so long even the clouds admire him!",
      ],
      fr: [
        "« Victor Foudroyant » — rapide comme l’éclair mais toujours rassurant.",
        "Vous sourirez de bonheur en l’air !",
        "Plus qu’un vol : une aventure pleine de rires.",
        "Il vole si longtemps que même les nuages l’admirent !",
      ],
      ru: [
        "«Победитель-молния» — быстрый как молния, но всегда спокойно и надёжно.",
        "Наверху вы будете улыбаться от радости!",
        "Это не просто полёт — это приключение, полное смеха.",
        "Летает так долго, что даже облака восхищаются!",
      ],
      zh: [
        "“雷霆胜者”——飞得快，但安全感也拉满。",
        "和他一起在天空漂浮，你会笑到合不拢嘴。",
        "不只是体验，更像一场充满笑声的冒险。",
        "飞得太久，连云都佩服：‘你不累吗？’",
      ],
      hi: [
        "‘लाइटनिंग विक्टर’—बिजली जैसी तेज़, फिर भी पूरी तरह भरोसेमंद।",
        "ऊपर आप खुशी से मुस्कुराते रहेंगे!",
        "सिर्फ फ्लाइट नहीं—हँसी से भरा एडवेंचर।",
        "इतना लंबा उड़ते हैं कि बादल भी कहें: ‘थके नहीं?’",
      ],
    },
    achievements: {
      vi: [
        "Với 7 năm kinh nghiệm làm bạn cùng trời mây, anh đã thực hiện hơn 4.000 chuyến bay đôi an toàn và chuyên nghiệp.",
        "Anh giữ kỷ lục Việt Nam #2 về thời gian bay đơn lâu nhất với 9 tiếng rưỡi liên tục, khẳng định sự bền bỉ và kỹ năng bay xuất sắc.",
        "Am hiểu sâu sắc về kỹ thuật dù lượn và điều kiện thời tiết, đảm bảo trải nghiệm an toàn và tuyệt vời cho khách hàng.",
      ],
      en: [
        "7 years of experience, 4,000+ safe professional tandem flights.",
        "Vietnam #2 record for longest solo flight: 9.5 consecutive hours.",
        "Deep expertise in techniques and weather conditions, ensuring safety and a great experience.",
      ],
      fr: [
        "7 ans d'expérience, 4 000+ vols tandem sûrs.",
        "Record Vietnam #2 : vol solo le plus long (9h30).",
        "Excellente maîtrise technique et météo pour une expérience sûre.",
      ],
      ru: [
        "7 лет опыта, 4 000+ безопасных профессиональных тандемных полётов.",
        "Рекорд Вьетнама #2 по длительности одиночного полёта: 9,5 часов подряд.",
        "Глубокое понимание техники и погодных условий для максимальной безопасности.",
      ],
      zh: [
        "7 年经验，完成 4,000+ 次安全专业双人飞行。",
        "越南单飞时长纪录第 2 名：连续 9.5 小时。",
        "精通飞行技术与天气判断，确保安全与高质量体验。",
      ],
      hi: [
        "7 साल का अनुभव, 4,000+ सुरक्षित प्रोफेशनल टैंडम उड़ानें।",
        "वियतनाम में #2 सबसे लंबी सोलो उड़ान: लगातार 9.5 घंटे।",
        "तकनीक और मौसम की गहरी समझ—सुरक्षित और शानदार अनुभव सुनिश्चित।",
      ],
    },
    flyingStyle: {
      vi: "Bay nhanh như tia chớp nhưng vẫn yên tâm tuyệt đối, chuyến phiêu lưu tràn ngập tiếng cười.",
      en: "Lightning-fast yet totally reassuring—an adventure full of laughter.",
      fr: "Rapide comme l’éclair mais rassurant — aventure pleine de rires.",
      ru: "Быстро, как молния, но при этом спокойно и надёжно — приключение с кучей смеха.",
      zh: "速度感十足但稳得住，安全又好玩，笑声不断。",
      hi: "बिजली जैसी तेज़ पर पूरी तरह सेफ़—हँसी-मज़ाक से भरा एडवेंचर।",
    },
  },

  {
    slug: "suman-thapa",
    name: "SUMAN THAPA",
    nickname: {
      vi: "Sky Ryder",
      en: "Sky Rider",
      fr: "Cavalier du Ciel",
      ru: "Небесный всадник",
      zh: "天空骑士",
      hi: "स्काई राइडर",
    },
    role: {
      vi: "Phi công Acro",
      en: "Acro Pilot",
      fr: "Pilote Acro",
      ru: "Акро-пилот",
      zh: "特技飞行员（Acro）",
      hi: "एक्रो पायलट",
    },
    experience: {
      vi: "3+ năm tại VN",
      en: "3+ years in Vietnam",
      fr: "3+ ans au Vietnam",
      ru: "3+ года во Вьетнаме",
      zh: "在越南 3+ 年",
      hi: "वियतनाम में 3+ साल",
    },
    flights: {
      vi: "Nhiều",
      en: "Many",
      fr: "Nombreux",
      ru: "Много",
      zh: "很多",
      hi: "कई",
    },
    hours: {
      vi: "1000+ giờ",
      en: "1000+ hours",
      fr: "1000+ heures",
      ru: "1000+ часов",
      zh: "1000+ 小时",
      hi: "1000+ घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/suman-thapa/suman-thapa.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/suman-thapa/hero-1.png",
      "/pilots/suman-thapa/hero-2.png",
      "/pilots/suman-thapa/hero-3.png",
      "/pilots/suman-thapa/hero-4.png",
      "/pilots/suman-thapa/hero-5.png",
      "/pilots/suman-thapa/content-1.png",
      "/pilots/suman-thapa/content-2.png",
      "/pilots/suman-thapa/content-3.png",
    ],
    specialties: {
      vi: ["Nhào lộn (Acro)", "Kỹ năng siêu đẳng"],
      en: ["Acrobatics (Acro)", "Superb skills"],
      fr: ["Acrobaties (Acro)", "Compétences exceptionnelles"],
      ru: ["Акробатика (Acro)", "Выдающиеся навыки"],
      zh: ["特技（Acro）", "超强技术"],
      hi: ["एक्रोबेटिक्स (Acro)", "बेहतरीन स्किल्स"],
    },
    certificates: {
      vi: ["Đào tạo chuyên nghiệp tại Nepal", "APPI (Mục tiêu)"],
      en: ["Professional training in Nepal", "APPI (Goal)"],
      fr: ["Formation professionnelle au Népal", "APPI (Objectif)"],
      ru: ["Профессиональная подготовка в Непале", "APPI (цель)"],
      zh: ["尼泊尔专业培训", "APPI（目标）"],
      hi: ["नेपाल में प्रोफेशनल ट्रेनिंग", "APPI (लक्ष्य)"],
    },
    bio: {
      vi: "Những video nhào lộn ngoạn mục tại Sapa hầu hết đều là của anh – phi công dày dặn kinh nghiệm, am hiểu sâu về dù lượn. Với anh, bay không chỉ là đam mê mà là sự nghiệp. Khách hàng gọi anh bằng cái tên đặc biệt: “Con của thần gió”.",
      en: "Most spectacular acro videos in Sapa are his—an experienced pilot with deep paragliding knowledge. For him, flying is a career, not just a passion. Passengers call him: 'Son of the Wind God'.",
      fr: "La plupart des vidéos acro spectaculaires à Sapa sont les siennes. Pour lui, voler est une carrière. Les clients l’appellent : « Fils du Dieu du Vent ».",
      ru: "Большинство зрелищных акро-видео в Сапе — его. Для него полёты — это профессия. Клиенты зовут его: «Сын Бога Ветра».",
      zh: "沙坝那些惊艳的特技视频，大多出自他手——经验丰富、懂技术。对他来说飞行不仅是爱好，更是事业。乘客叫他“风神之子”。",
      hi: "सापा के कई शानदार एक्रो वीडियो उन्हीं के हैं—गहरी तकनीकी समझ वाले अनुभवी पायलट। उनके लिए उड़ान सिर्फ शौक नहीं, करियर है। लोग उन्हें ‘Wind God का बेटा’ कहते हैं।",
    },
    funFacts: {
      vi: [
        "Anh ấy là người mà khi gió nổi lên — dù chưa cất cánh — cũng có thể nghe thấy tiếng trái tim anh reo: “Chúng ta cùng bay nhé!”",
        "Anh ấy say mê dù lượn như người ta say tách cà phê buổi sáng — không thể thiếu, không thể ngừng.",
        "Với anh, mỗi cú nhào lộn là một nụ cười khẳng định rằng: “Mình sống là để bay.”",
      ],
      en: [
        "When the wind rises—before takeoff—you can almost hear his heart: 'Let’s fly together!'",
        "He loves paragliding like morning coffee—indispensable and unstoppable.",
        "Every acro move is his smile saying: 'I live to fly.'",
      ],
      fr: [
        "Quand le vent se lève, on dirait que son cœur dit : « Volons ensemble ! »",
        "Il aime le parapente comme le café du matin : indispensable.",
        "Chaque figure acro est un sourire : « Je vis pour voler. »",
      ],
      ru: [
        "Когда поднимается ветер — ещё до взлёта — кажется, его сердце говорит: «Полетаем вместе!»",
        "Любит парапланеризм как утренний кофе — без этого не может.",
        "Каждый акро-трюк — улыбка: «Я живу, чтобы летать».",
      ],
      zh: [
        "风一起来，就算还没起飞，你也能“听到”他心里在说：‘一起飞吧！’",
        "他对滑翔伞的热爱像早晨的咖啡——离不开、停不下。",
        "每一次特技翻滚，都是他在用笑容说：‘我为飞行而生。’",
      ],
      hi: [
        "हवा चलने लगे तो टेक-ऑफ से पहले ही लगता है उनका दिल कह रहा हो: ‘चलो साथ उड़ें!’",
        "पैराग्लाइडिंग उनके लिए सुबह की कॉफी जैसी—बिना नहीं चलती।",
        "हर एक्रो मूव उनके लिए मुस्कान है: ‘मैं उड़ने के लिए जीता हूँ।’",
      ],
    },
    achievements: {
      vi: [
        "Hoàn thành khoá đào tạo huấn luyện phi công chuyên nghiệp tại Nepal",
        "Phi công acro với kỹ năng nhào lộn siêu đẳng, thuần thục nhiều động tác acro",
        "Anh có hơn 1.000 giờ bay đôi chuyên nghiệp, luôn giữ an toàn tuyệt đối",
        "Đã hoạt động hơn 3 năm tại Việt Nam, có hiểu biết sâu sắc về địa hình và khí tượng trong nước",
        "Anh đặt mục tiêu trở thành huấn luyện viên dù lượn được công nhận APPI",
      ],
      en: [
        "Completed professional pilot training in Nepal.",
        "Acro pilot proficient in many advanced maneuvers.",
        "1,000+ hours of professional tandem flying with absolute safety.",
        "3+ years operating in Vietnam with strong terrain & weather knowledge.",
        "Aims to become an APPI-certified instructor.",
      ],
      fr: [
        "Formation professionnelle de pilote au Népal.",
        "Pilote acro maîtrisant de nombreuses figures avancées.",
        "1 000+ heures de vols tandem en sécurité.",
        "3+ ans au Vietnam, bonne connaissance du terrain et de la météo.",
        "Objectif : devenir instructeur certifié APPI.",
      ],
      ru: [
        "Окончил профессиональное обучение пилотов в Непале.",
        "Пилот-акробат, владеет множеством сложных элементов.",
        "1 000+ часов тандемных полётов с максимальной безопасностью.",
        "3+ года работы во Вьетнаме, хорошее знание рельефа и метео.",
        "Цель — стать инструктором APPI.",
      ],
      zh: [
        "完成尼泊尔专业飞行员培训。",
        "特技伞飞行员，掌握多种高阶动作。",
        "专业双人飞行 1,000+ 小时，安全把控到位。",
        "在越南工作 3+ 年，熟悉本地地形与气象。",
        "目标成为 APPI 认证教练。",
      ],
      hi: [
        "नेपाल में प्रोफेशनल पायलट ट्रेनिंग पूर्ण।",
        "एक्रो पायलट—कई एडवांस्ड मूव्स में दक्ष।",
        "1,000+ घंटे प्रोफेशनल टैंडम उड़ान, सेफ़्टी टॉप-प्रायोरिटी।",
        "वियतनाम में 3+ साल—लोकल टेर्रेन/मौसम की गहरी समझ।",
        "लक्ष्य: APPI-सर्टिफ़ाइड इंस्ट्रक्टर बनना।",
      ],
    },
    flyingStyle: {
      vi: "Nhào lộn ngoạn mục, kỹ năng Acro siêu đẳng, 'Con của thần gió'.",
      en: "Spectacular acrobatics, superb Acro skills—'Son of the Wind God'.",
      fr: "Acrobaties spectaculaires, compétences Acro — « Fils du Dieu du Vent ».",
      ru: "Зрелищная акробатика, выдающиеся навыки — «Сын Бога Ветра».",
      zh: "特技动作漂亮、操控扎实——“风神之子”。",
      hi: "शानदार एक्रोबेटिक्स, टॉप-क्लास एक्रो स्किल्स—‘Wind God का बेटा’।",
    },
  },

  {
    slug: "alish-thapa",
    name: "ALISH THAPA",
    nickname: {
      vi: "Phantom bầu trời",
      en: "Sky Phantom",
      fr: "Fantôme du Ciel",
      ru: "Небесный фантом",
      zh: "天空幻影",
      hi: "स्काई फैंटम",
    },
    role: {
      vi: "Huấn luyện viên SIV & APPI, Phi công Acro",
      en: "SIV & APPI Instructor, Acro Pilot",
      fr: "Instructeur SIV & APPI, Pilote Acro",
      ru: "Инструктор SIV и APPI, акро-пилот",
      zh: "SIV & APPI 教练，特技飞行员（Acro）",
      hi: "SIV व APPI इंस्ट्रक्टर, एक्रो पायलट",
    },
    experience: {
      vi: "Nhiều năm",
      en: "Many years",
      fr: "De nombreuses années",
      ru: "Много лет",
      zh: "多年经验",
      hi: "कई वर्षों का अनुभव",
    },
    flights: {
      vi: "Nhiều",
      en: "Many",
      fr: "Nombreux",
      ru: "Много",
      zh: "很多",
      hi: "कई",
    },
    hours: {
      vi: "Nhiều giờ",
      en: "Many hours",
      fr: "De nombreuses heures",
      ru: "Много часов",
      zh: "许多小时",
      hi: "कई घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/alish-thapa/alish-thapa.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/alish-thapa/hero-1.png",
      "/pilots/alish-thapa/hero-2.png",
      "/pilots/alish-thapa/hero-3.png",
      "/pilots/alish-thapa/hero-4.png",
      "/pilots/alish-thapa/hero-5.png",
      "/pilots/alish-thapa/content-1.png",
      "/pilots/alish-thapa/content-2.png",
      "/pilots/alish-thapa/content-3.png",
    ],
    specialties: {
      vi: ["Huấn luyện APPI", "Nhảy dù (Skydive)"],
      en: ["APPI training", "Skydiving"],
      fr: ["Formation APPI", "Parachutisme"],
      ru: ["Обучение APPI", "Прыжки с парашютом"],
      zh: ["APPI 培训", "跳伞（Skydive）"],
      hi: ["APPI ट्रेनिंग", "स्काइडाइविंग"],
    },
    certificates: {
      vi: ["Huấn luyện viên APPI", "Huấn luyện viên nhảy dù USPA"],
      en: ["APPI Instructor", "USPA Skydiving Instructor"],
      fr: ["Instructeur APPI", "Instructeur parachutisme USPA"],
      ru: ["Инструктор APPI", "Инструктор USPA по парашютному спорту"],
      zh: ["APPI 教练", "USPA 跳伞教练"],
      hi: ["APPI इंस्ट्रक्टर", "USPA स्काइडाइविंग इंस्ट्रक्टर"],
    },
    bio: {
      vi: "Huấn luyện viên dù lượn chuyên nghiệp với chứng chỉ APPI, được nhiều tổ chức quốc tế mời giảng dạy. Không chỉ giỏi chuyên môn, anh còn là phi công vui tính, thân thiện, luôn mang đến những chuyến bay an toàn, thú vị và khiến hành khách quý mến ngay từ lần gặp đầu tiên.",
      en: "Professional APPI-certified instructor invited internationally. Highly skilled, humorous, and friendly—always safe, fun flights that passengers love from the first meeting.",
      fr: "Instructeur certifié APPI, invité par des organisations internationales. Compétent, drôle et amical — des vols sûrs et plaisants dès la première rencontre.",
      ru: "Профессиональный инструктор APPI, приглашённый международными организациями. Очень опытный, с юмором и дружелюбный — полёты всегда безопасные и интересные.",
      zh: "APPI 认证专业教练，多次受国际机构邀请授课。技术硬、性格也超友好幽默，飞行安全又好玩，第一次见面就让人喜欢。",
      hi: "APPI-सर्टिफ़ाइड प्रोफेशनल इंस्ट्रक्टर—कई इंटरनेशनल ऑर्गनाइज़ेशंस द्वारा आमंत्रित। स्किल्ड, मज़ेदार और फ्रेंडली—हर फ्लाइट सुरक्षित और एंजॉयबल।",
    },
    funFacts: {
      vi: [
        "Anh ấy là một trong những phi công dù lượn hàng đầu tại Nepal. Với kinh nghiệm phong phú, anh đã được mời huấn luyện tại nhiều điểm bay nổi tiếng như Việt Nam, Trung Quốc, Thái Lan, nơi anh chia sẻ đam mê và kỹ thuật bay đỉnh cao.",
        "Phong cách huấn luyện của anh luôn vui vẻ, giúp học viên bay như đang nhảy múa trên không trung — không chỉ học bay mà còn học cách yêu bầu trời.",
        "Anh truyền cảm hứng và đam mê cho du khách cùng bay, và nhiều người trong số họ đã trở thành phi công chuyên nghiệp sau khi trải nghiệm bay cùng anh.",
      ],
      en: [
        "One of Nepal’s top pilots, invited to train in Vietnam, China, Thailand—sharing passion and elite techniques.",
        "Cheerful training style—students feel like dancing in the air while learning.",
        "He inspires passengers; many later became professional pilots after flying with him.",
      ],
      fr: [
        "Parmi les meilleurs pilotes au Népal, invité à former au Vietnam, en Chine, en Thaïlande.",
        "Style d'enseignement joyeux : on apprend en « dansant » dans l'air.",
        "Il inspire les passagers — beaucoup sont devenus pilotes professionnels après l’avoir rencontré.",
      ],
      ru: [
        "Один из ведущих пилотов Непала, приглашался обучать во Вьетнаме, Китае, Таиланде.",
        "Весёлый стиль обучения — ученики будто танцуют в воздухе.",
        "Вдохновляет пассажиров — многие после полёта с ним стали профессиональными пилотами.",
      ],
      zh: [
        "尼泊尔顶尖飞行员之一，受邀在越南、中国、泰国等地授课，分享高阶技巧。",
        "教学风格轻松有趣，让学员像在空中跳舞一样学会飞行、爱上天空。",
        "他很会点燃热情，很多乘客体验后走上了成为专业飞行员的道路。",
      ],
      hi: [
        "नेपाल के टॉप पायलट्स में से एक—वियतनाम, चीन, थाईलैंड जैसे स्थानों पर ट्रेनिंग देने के लिए आमंत्रित।",
        "खुशनुमा ट्रेनिंग स्टाइल—स्टूडेंट्स को हवा में ‘डांस’ जैसा फील कराते हैं।",
        "पैसेंजर्स में पैशन जगाते हैं—कई लोग उनके साथ उड़कर आगे चलकर प्रोफेशनल पायलट बने।",
      ],
    },
    achievements: {
      vi: [
        "Người hướng dẫn chính & S&TA (An toàn và đánh giá bay) tại Skydive Chiang Mai",
        "Giám đốc điều hành tại Insky Skydive",
        "Giám đốc điều hành tại Everest Paragliding",
        "Phi công dù lượn chuyên nghiệp & huấn luyện viên tại Fishtail Nepal Paragliding",
        "Huấn luyện viên dù lượn APPI",
        "Huấn luyện viên nhảy dù (AFF-I, TAN-I) theo chuẩn USPA",
      ],
      en: [
        "Chief Instructor & S&TA at Skydive Chiang Mai",
        "CEO at Insky Skydive",
        "CEO at Everest Paragliding",
        "Pilot & instructor at Fishtail Nepal Paragliding",
        "APPI Paragliding Instructor",
        "USPA Skydive Instructor (AFF-I, TAN-I)",
      ],
      fr: [
        "Instructeur en chef & S&TA à Skydive Chiang Mai",
        "PDG chez Insky Skydive",
        "PDG chez Everest Paragliding",
        "Pilote & instructeur chez Fishtail Nepal Paragliding",
        "Instructeur APPI",
        "Instructeur USPA (AFF-I, TAN-I)",
      ],
      ru: [
        "Главный инструктор и S&TA в Skydive Chiang Mai",
        "CEO в Insky Skydive",
        "CEO в Everest Paragliding",
        "Пилот и инструктор в Fishtail Nepal Paragliding",
        "Инструктор APPI",
        "Инструктор USPA (AFF-I, TAN-I)",
      ],
      zh: [
        "Skydive Chiang Mai 首席教练 & S&TA（安全/训练评估）",
        "Insky Skydive CEO",
        "Everest Paragliding CEO",
        "Fishtail Nepal Paragliding 专业飞行员/教练",
        "APPI 滑翔伞教练",
        "USPA 跳伞教练（AFF-I，TAN-I）",
      ],
      hi: [
        "Skydive Chiang Mai में Chief Instructor & S&TA (Safety/Training Advisor)",
        "Insky Skydive के CEO",
        "Everest Paragliding के CEO",
        "Fishtail Nepal Paragliding में Pilot & Instructor",
        "APPI Paragliding Instructor",
        "USPA Skydive Instructor (AFF-I, TAN-I)",
      ],
    },
    flyingStyle: {
      vi: "Huấn luyện viên chuyên nghiệp, vui tính, thân thiện, bay an toàn và thú vị.",
      en: "Professional instructor—humorous, friendly, safe and enjoyable flights.",
      fr: "Instructeur pro — drôle, amical, vols sûrs et agréables.",
      ru: "Профессиональный инструктор — с юмором, дружелюбный, безопасные и интересные полёты.",
      zh: "专业教练，幽默友好，飞行安全又有趣。",
      hi: "प्रोफेशनल इंस्ट्रक्टर—फन और फ्रेंडली; सुरक्षित व एंजॉयबल फ्लाइट।",
    },
  },

  {
    slug: "bishal-thapa",
    name: "BISHAL THAPA",
    nickname: {
      vi: "Đặc nhiệm cánh gió",
      en: "Wind Commando",
      fr: "Commando du Vent",
      ru: "Ветряной коммандос",
      zh: "风翼特勤",
      hi: "विंड कमांडो",
    },
    role: {
      vi: "Phi công",
      en: "Pilot",
      fr: "Pilote",
      ru: "Пилот",
      zh: "飞行员",
      hi: "पायलट",
    },
    experience: {
      vi: "Từ 2016",
      en: "Since 2016",
      fr: "Depuis 2016",
      ru: "С 2016 года",
      zh: "自 2016 年起",
      hi: "2016 से",
    },
    flights: {
      vi: "3000+",
      en: "3000+",
      fr: "3000+",
      ru: "3000+",
      zh: "3000+",
      hi: "3000+",
    },
    hours: {
      vi: "1000+ giờ",
      en: "1000+ hours",
      fr: "1000+ heures",
      ru: "1000+ часов",
      zh: "1000+ 小时",
      hi: "1000+ घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/bishal-thapa/bishal-thapa.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/bishal-thapa/hero-1.png",
      "/pilots/bishal-thapa/hero-2.png",
      "/pilots/bishal-thapa/hero-3.png",
      "/pilots/bishal-thapa/hero-4.png",
      "/pilots/bishal-thapa/hero-5.png",
      "/pilots/bishal-thapa/content-1.png",
      "/pilots/bishal-thapa/content-2.png",
      "/pilots/bishal-thapa/content-3.png",
    ],
    specialties: {
      vi: ["Hạ cánh chính xác", "Vui vẻ", "Năng lượng"],
      en: ["Precision landing", "Fun", "Energy"],
      fr: ["Atterrissage de précision", "Fun", "Énergie"],
      ru: ["Точность приземления", "Весело", "Энергия"],
      zh: ["精准降落", "氛围开心", "满满能量"],
      hi: ["प्रिसिजन लैंडिंग", "मज़ेदार", "फुल-एनर्जी"],
    },
    certificates: {
      vi: ["Vô địch Indian Accuracy Cup", "Giải Pre-World Cup"],
      en: ["Indian Accuracy Cup Champion", "Pre-World Cup Award"],
      fr: ["Champion Indian Accuracy Cup", "Prix Pre-World Cup"],
      ru: ["Чемпион Indian Accuracy Cup", "Награда Pre-World Cup"],
      zh: ["Indian Accuracy Cup 冠军", "Pre-World Cup 奖项"],
      hi: ["Indian Accuracy Cup चैंपियन", "Pre-World Cup अवॉर्ड"],
    },
    bio: {
      vi: "Đam mê hạ cánh chính xác, anh luôn đặt mục tiêu chạm đúng tâm với sai số tối thiểu. Nhờ đó, mỗi chuyến bay đều an toàn như lập trình. Vui vẻ, dễ gần, anh luôn lắng nghe và quan tâm đến cảm xúc của khách để mang lại trải nghiệm bay trọn vẹn nhất.",
      en: "Passionate about precision landing, he aims for the center with minimal error—making flights as safe as programmed. Cheerful and caring, he listens closely to ensure the best experience.",
      fr: "Passionné d'atterrissage de précision, il vise le centre avec une erreur minimale — des vols sûrs comme programmés. Joyeux et attentionné.",
      ru: "Увлечён точностью приземления: минимальная ошибка — полёт безопасен «как по программе». Весёлый и заботливый, всегда прислушивается к пассажирам.",
      zh: "热爱精准降落，目标就是“稳稳落在中心点”。因此每次飞行都像写好程序一样安全。性格开朗、很会照顾乘客情绪。",
      hi: "प्रिसिजन लैंडिंग के शौकीन—सेंटर-हिट का लक्ष्य, न्यूनतम त्रुटि; इसलिए हर उड़ान ‘प्रोग्राम्ड’ जैसी सुरक्षित। खुशमिज़ाज और केयरिंग, पैसेंजर की फीलिंग्स पर हमेशा ध्यान।",
    },
    funFacts: {
      vi: [
        "Bishal Thapa luôn mang theo cả “cục pin năng lượng” và nụ cười rạng rỡ trong mỗi chuyến bay. Anh chàng vui tính, dễ mến này biết cách làm cho bạn cảm giác như đang bay cùng một người bạn thân chứ không phải phi công!",
        "Đam mê hạ cánh chuẩn từng milimet, Bishal biến mỗi cú đáp đất thành một “vũ điệu” đẹp mắt trên bầu trời.",
        "Bay cùng anh, bạn không chỉ học bay mà còn có một chuyến phiêu lưu đầy tiếng cười và cảm xúc!",
      ],
      en: [
        "Always brings a full battery of energy and a bright smile—feels like flying with a close friend!",
        "Turns every precision landing into a beautiful sky dance.",
        "An adventure full of laughter and emotions!",
      ],
      fr: [
        "Toujours une énergie incroyable et un grand sourire — comme voler avec un ami !",
        "Chaque atterrissage de précision devient une danse dans le ciel.",
        "Une aventure pleine de rires et d'émotions !",
      ],
      ru: [
        "Всегда с «полным зарядом энергии» и яркой улыбкой — будто летишь с другом!",
        "Каждое точное приземление превращает в красивый «танец».",
        "Приключение, полное смеха и эмоций!",
      ],
      zh: [
        "自带“能量电池”和灿烂笑容，飞起来像和好朋友一起玩！",
        "把毫米级精准降落变成空中“舞步”。",
        "和他飞，不止是体验，更是一场笑声与情绪拉满的冒险！",
      ],
      hi: [
        "हर उड़ान में फुल-एनर्जी और ब्राइट स्माइल—ऐसा लगेगा जैसे किसी करीबी दोस्त के साथ उड़ रहे हों!",
        "मिलीमीटर-परफेक्ट लैंडिंग को आसमान की ‘डांस मूव’ बना देते हैं।",
        "उनके साथ उड़ान = हँसी और इमोशन्स से भरा एडवेंचर!",
      ],
    },
    achievements: {
      vi: [
        "Anh bắt đầu học dù lượn từ năm 2016 và trở thành phi công tandem chuyên nghiệp từ năm 2019",
        "Giải Pre-World Cup Mizoram Open Accuracy Championship 2018 - Vị trí thứ hai cá nhân, đội tuyển đạt vị trí nhất toàn đoàn",
        "Giải Accuracy Paragliding Pre-World Cup 2023 - Vị trí thứ hai cá nhân, đội tuyển đứng đầu toàn đoàn",
        "Giải Indian Accuracy Cup Bilaspur - Vô địch cá nhân",
        "Kinh nghiệm bay tandem: hơn 3000 chuyến bay, với tổng thời gian bay an toàn trên 1000 giờ.",
      ],
      en: [
        "Started in 2016; became a professional tandem pilot in 2019.",
        "Mizoram Open Accuracy Pre-World Cup 2018: 2nd individual; team 1st overall.",
        "Accuracy Paragliding Pre-World Cup 2023: 2nd individual; team 1st overall.",
        "Indian Accuracy Cup Bilaspur: individual champion.",
        "3,000+ tandem flights; 1,000+ safe flight hours.",
      ],
      fr: [
        "Débute en 2016; pilote tandem pro depuis 2019.",
        "Pre-World Cup Mizoram 2018 : 2e individuel; équipe 1re.",
        "Pre-World Cup 2023 : 2e individuel; équipe 1re.",
        "Indian Accuracy Cup Bilaspur : champion individuel.",
        "3 000+ vols tandem; 1 000+ heures en sécurité.",
      ],
      ru: [
        "Начал в 2016; профессиональный тандем-пилот с 2019.",
        "Pre-World Cup Mizoram 2018: 2-е место лично; команда 1-я.",
        "Pre-World Cup 2023: 2-е место лично; команда 1-я.",
        "Indian Accuracy Cup Bilaspur: чемпион лично.",
        "3 000+ тандемных полётов; 1 000+ часов безопасного налёта.",
      ],
      zh: [
        "2016 年开始学习，2019 年成为专业双人飞行员。",
        "2018 Mizoram Open Accuracy（Pre-World Cup）：个人第 2，团队总冠军。",
        "2023 Accuracy Paragliding Pre-World Cup：个人第 2，团队总冠军。",
        "Indian Accuracy Cup Bilaspur：个人冠军。",
        "双人飞行 3,000+ 次，安全飞行 1,000+ 小时。",
      ],
      hi: [
        "2016 में शुरू किया; 2019 से प्रोफेशनल टैंडम पायलट।",
        "Pre-World Cup Mizoram Open Accuracy 2018: व्यक्तिगत 2nd, टीम 1st ओवरऑल।",
        "Accuracy Paragliding Pre-World Cup 2023: व्यक्तिगत 2nd, टीम 1st ओवरऑल।",
        "Indian Accuracy Cup Bilaspur: व्यक्तिगत चैंपियन।",
        "3,000+ टैंडम उड़ानें; 1,000+ सुरक्षित उड़ान घंटे।",
      ],
    },
    flyingStyle: {
      vi: "Hạ cánh chính xác, an toàn như lập trình, vui vẻ và đầy năng lượng.",
      en: "Precision landing, safe as programmed—cheerful and energetic.",
      fr: "Atterrissage précis, sécurité « programmée » — joyeux et énergique.",
      ru: "Точное приземление, безопасно «как по программе», весело и энергично.",
      zh: "精准降落、像程序一样稳；又开心又有能量。",
      hi: "प्रिसिजन लैंडिंग, ‘प्रोग्राम्ड’ जैसी सेफ़्टी—और फुल-एनर्जी।",
    },
  },

  {
    slug: "bishal-skyboy",
    name: "BISHAL SKYBOY",
    nickname: {
      vi: "Skyboy",
      en: "Skyboy",
      fr: "Skyboy",
      ru: "Скайбой",
      zh: "天空男孩",
      hi: "स्काईबॉय",
    },
    role: {
      vi: "Phi công Acro, Phi công thi đấu",
      en: "Acro Pilot, Competition Pilot",
      fr: "Pilote Acro, Pilote de compétition",
      ru: "Акро-пилот, пилот соревнований",
      zh: "特技飞行员（Acro），竞技飞行员",
      hi: "एक्रो पायलट, प्रतियोगी पायलट",
    },
    experience: {
      vi: "Nhiều năm",
      en: "Many years",
      fr: "De nombreuses années",
      ru: "Много лет",
      zh: "多年经验",
      hi: "कई वर्षों का अनुभव",
    },
    flights: {
      vi: "Nhiều",
      en: "Many",
      fr: "Nombreux",
      ru: "Много",
      zh: "很多",
      hi: "कई",
    },
    hours: {
      vi: "Nhiều giờ",
      en: "Many hours",
      fr: "De nombreuses heures",
      ru: "Много часов",
      zh: "许多小时",
      hi: "कई घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/bishal-skyboy/bishal-skyboy.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/bishal-skyboy/hero-1.png",
      "/pilots/bishal-skyboy/hero-2.png",
      "/pilots/bishal-skyboy/hero-3.png",
      "/pilots/bishal-skyboy/hero-4.png",
      "/pilots/bishal-skyboy/hero-5.png",
      "/pilots/bishal-skyboy/content-1.png",
      "/pilots/bishal-skyboy/content-2.png",
      "/pilots/bishal-skyboy/content-3.png",
    ],
    specialties: {
      vi: ["Nhào lộn (Acro)", "Kỹ thuật đỉnh cao"],
      en: ["Acrobatics (Acro)", "Top-tier technique"],
      fr: ["Acrobaties (Acro)", "Technique de haut niveau"],
      ru: ["Акробатика (Acro)", "Техника высшего уровня"],
      zh: ["特技（Acro）", "顶级技术"],
      hi: ["एक्रोबेटिक्स (Acro)", "टॉप-टियर टेक्नीक"],
    },
    certificates: {
      vi: ["Phi công chuyên nghiệp Nepal"],
      en: ["Nepal Professional Pilot"],
      fr: ["Pilote professionnel (Népal)"],
      ru: ["Профессиональный пилот (Непал)"],
      zh: ["尼泊尔职业飞行员"],
      hi: ["नेपाल प्रोफेशनल पायलट"],
    },
    bio: {
      vi: "Phi công chuyên nghiệp đến từ Nepal, nổi tiếng toàn cầu với kỹ năng nhào lộn Acro mãn nhãn. Không chỉ chinh phục bầu trời bằng kỹ thuật đỉnh cao, anh còn là phi công bay đôi dày dạn, mang đến trải nghiệm bay hưng phấn và khó quên cho mọi hành khách",
      en: "Professional pilot from Nepal, globally renowned for spectacular Acro skills. Also an experienced tandem pilot, delivering an exhilarating, unforgettable experience.",
      fr: "Pilote pro du Népal, réputé mondialement pour ses acrobaties Acro. Aussi pilote tandem expérimenté, pour un vol inoubliable.",
      ru: "Профессиональный пилот из Непала, всемирно известный зрелищной акро-техникой. Опытный тандем-пилот, дарит яркие и незабываемые впечатления.",
      zh: "来自尼泊尔的职业飞行员，以震撼的特技飞行闻名全球；同时也是经验丰富的双人飞行员，体验刺激难忘。",
      hi: "नेपाल के प्रोफेशनल पायलट—स्पेक्टैक्युलर एक्रो स्किल्स के लिए दुनिया-भर में मशहूर। अनुभवी टैंडम पायलट, जोश-भरा और यादगार अनुभव देते हैं।",
    },
    funFacts: {
      vi: ["Nổi tiếng toàn cầu với kỹ năng nhào lộn Acro mãn nhãn.", "Mang đến trải nghiệm bay hưng phấn và khó quên."],
      en: ["Globally renowned for spectacular Acro skills.", "Brings an exhilarating and unforgettable flying experience."],
      fr: ["De renommée mondiale pour ses acrobaties Acro.", "Offre une expérience exaltante et inoubliable."],
      ru: ["Всемирно известен зрелищными навыками акро.", "Дарит волнующий и незабываемый опыт полёта."],
      zh: ["以精彩的 Acro 特技闻名全球。", "带来刺激、难忘的飞行体验。"],
      hi: ["शानदार एक्रो स्किल्स के लिए ग्लोबल पहचान।", "रोमांचक और यादगार उड़ान अनुभव।"],
    },
    achievements: {
      vi: ["Phi công chuyên nghiệp đến từ Nepal.", "Nổi tiếng toàn cầu với kỹ năng nhào lộn Acro.", "Phi công bay đôi dày dạn kinh nghiệm."],
      en: ["Professional pilot from Nepal.", "Globally renowned for Acro skills.", "Experienced tandem pilot."],
      fr: ["Pilote professionnel du Népal.", "Réputé mondialement pour l’Acro.", "Pilote tandem expérimenté."],
      ru: ["Профессиональный пилот из Непала.", "Всемирно известен акро-навыками.", "Опытный тандем-пилот."],
      zh: ["尼泊尔职业飞行员。", "全球知名 Acro 特技。", "经验丰富的双人飞行员。"],
      hi: ["नेपाल से प्रोफेशनल पायलट।", "एक्रो स्किल्स के लिए ग्लोबल पहचान।", "अनुभवी टैंडम पायलट।"],
    },
    flyingStyle: {
      vi: "Kỹ năng nhào lộn Acro mãn nhãn, kỹ thuật đỉnh cao, trải nghiệm hưng phấn.",
      en: "Spectacular Acro skills, top-tier technique, exhilarating experience.",
      fr: "Acro spectaculaire, technique de haut niveau, expérience exaltante.",
      ru: "Зрелищные акро-элементы, высший уровень техники, яркие эмоции.",
      zh: "特技漂亮、技术顶级，体验非常带劲。",
      hi: "स्पेक्टैक्युलर एक्रो, टॉप-टियर टेक्नीक, जबरदस्त रोमांच।",
    },
  },

  {
    slug: "subash-thapa",
    name: "SUBASH THAPA",
    nickname: {
      vi: "Kỵ sỹ không trung",
      en: "Sky Knight",
      fr: "Chevalier du Ciel",
      ru: "Небесный рыцарь",
      zh: "空中骑士",
      hi: "स्काई नाइट",
    },
    role: {
      vi: "Huấn luyện viên, Phi công Acro",
      en: "Instructor, Acro Pilot",
      fr: "Instructeur, Pilote Acro",
      ru: "Инструктор, акро-пилот",
      zh: "教练，特技飞行员（Acro）",
      hi: "इंस्ट्रक्टर, एक्रो पायलट",
    },
    experience: {
      vi: "3+ năm tại VN",
      en: "3+ years in Vietnam",
      fr: "3+ ans au Vietnam",
      ru: "3+ года во Вьетнаме",
      zh: "在越南 3+ 年",
      hi: "वियतनाम में 3+ साल",
    },
    flights: {
      vi: "Nhiều",
      en: "Many",
      fr: "Nombreux",
      ru: "Много",
      zh: "很多",
      hi: "कई",
    },
    hours: {
      vi: "4000+ giờ",
      en: "4000+ hours",
      fr: "4000+ heures",
      ru: "4000+ часов",
      zh: "4000+ 小时",
      hi: "4000+ घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/subash-thapa/subash-thapa.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/subash-thapa/hero-1.png",
      "/pilots/subash-thapa/hero-2.png",
      "/pilots/subash-thapa/hero-3.png",
      "/pilots/subash-thapa/hero-4.png",
      "/pilots/subash-thapa/hero-5.png",
      "/pilots/subash-thapa/content-1.png",
      "/pilots/subash-thapa/content-2.png",
      "/pilots/subash-thapa/content-3.png",
    ],
    specialties: {
      vi: ["Huấn luyện", "Âm nhạc", "Nhảy dù"],
      en: ["Training", "Music", "Skydiving"],
      fr: ["Formation", "Musique", "Parachutisme"],
      ru: ["Обучение", "Музыка", "Прыжки с парашютом"],
      zh: ["培训", "音乐", "跳伞"],
      hi: ["ट्रेनिंग", "म्यूज़िक", "स्काइडाइविंग"],
    },
    certificates: {
      vi: ["Phi công trưởng"],
      en: ["Chief Pilot"],
      fr: ["Pilote en chef"],
      ru: ["Главный пилот"],
      zh: ["首席飞行员"],
      hi: ["चीफ पायलट"],
    },
    bio: {
      vi: "Huấn luyện viên dù lượn chuyên nghiệp đã đào tạo rất nhiều phi công dù lượn trên thế giới. Anh không chỉ có đam mê dù lượn mà còn yêu thích âm nhạc, chính vì thế mọi chuyến bay đôi cùng anh đều sống động và đầy cảm hứng",
      en: "Professional instructor who trained many pilots worldwide. Loves both paragliding and music—so every tandem flight is lively and inspiring.",
      fr: "Instructeur pro ayant formé de nombreux pilotes. Passionné de parapente et de musique : chaque vol tandem est vivant et inspirant.",
      ru: "Профессиональный инструктор, обучивший многих пилотов по миру. Любит и парапланеризм, и музыку — поэтому каждый тандемный полёт яркий и вдохновляющий.",
      zh: "专业教练，培养了许多飞行员。热爱滑翔伞也热爱音乐，所以和他一起飞总是很有氛围、很有灵感。",
      hi: "प्रोफेशनल इंस्ट्रक्टर—दुनिया भर में कई पायलट्स को ट्रेन किया। पैराग्लाइडिंग के साथ संगीत-प्रेम भी, इसलिए हर टैंडम फ्लाइट जीवंत और प्रेरणादायक होती है।",
    },
    funFacts: {
      vi: [
        "Subash Thapa không chỉ là huấn luyện viên dù lượn siêu đỉnh mà còn là “DJ trên không” với tình yêu âm nhạc cháy bỏng, khiến mỗi chuyến bay đôi như một bữa tiệc vui nhộn giữa trời xanh!",
        "Đã gần 3 năm ở Việt Nam, Subash thuộc lòng mọi cung đường đặc thù về thời tiết, giúp chuyến bay của bạn mượt mà như mơ.",
        "Bay cùng anh, bạn không chỉ trải nghiệm cái sải cánh bền bỉ mà còn có thêm một người bạn vui tính, đầy năng lượng tích cực!",
      ],
      en: [
        "Not only a top instructor but also an 'aerial DJ'—every flight feels like a party in the sky!",
        "Nearly 3 years in Vietnam—knows local weather routes by heart for smooth flights.",
        "You gain a cheerful friend full of positive energy!",
      ],
      fr: [
        "Instructeur au top et « DJ aérien » : chaque vol ressemble à une fête !",
        "Près de 3 ans au Vietnam : maîtrise des routes météo locales.",
        "Un ami joyeux plein d'énergie positive !",
      ],
      ru: [
        "Не только топ-инструктор, но и «воздушный DJ» — каждый полёт как вечеринка!",
        "Почти 3 года во Вьетнаме — отлично знает локальные погодные маршруты.",
        "С ним вы получите ещё и весёлого друга с позитивной энергией!",
      ],
      zh: [
        "不仅是超强教练，还是“空中DJ”——每次飞行都像一场天空派对！",
        "在越南近 3 年，把本地天气/航线摸得门儿清，飞行顺滑像做梦。",
        "和他飞，你会收获一个超开心、充满正能量的朋友！",
      ],
      hi: [
        "टॉप-क्लास इंस्ट्रक्टर और ‘एरियल DJ’—हर फ्लाइट आसमान में पार्टी जैसी!",
        "वियतनाम में लगभग 3 साल—लोकल मौसम रूट्स की शानदार समझ, फ्लाइट स्मूद।",
        "उनके साथ आपको पॉज़िटिव एनर्जी वाला मज़ेदार दोस्त भी मिल जाएगा!",
      ],
    },
    achievements: {
      vi: [
        "Phi công trưởng, huấn luyện viên dù lượn và nhảy dù tại Pokhara.",
        "Phi công trưởng tại Nepal Acro Paragliding.",
        "Từng đảm nhiệm vị trí Phi công trưởng tại New Para World Paragliding.",
        "Sở hữu hơn 4.000 giờ bay tandem chuyên nghiệp, luôn tối ưu hoá an toàn của hành khách lên hàng đầu.",
        "Với hơn 4 năm kinh nghiệm hoạt động tại Việt Nam, anh có kiến thức vững chắc về địa hình và điều kiện thời tiết",
      ],
      en: [
        "Chief pilot; paragliding & skydiving instructor in Pokhara.",
        "Chief pilot at Nepal Acro Paragliding.",
        "Former Chief Pilot at New Para World Paragliding.",
        "4,000+ hours of professional tandem flying, prioritizing safety.",
        "4+ years in Vietnam with strong terrain & weather knowledge.",
      ],
      fr: [
        "Pilote en chef; instructeur parapente & parachutisme à Pokhara.",
        "Pilote en chef chez Nepal Acro Paragliding.",
        "Ancien pilote en chef chez New Para World Paragliding.",
        "4 000+ heures tandem pro, sécurité prioritaire.",
        "4+ ans au Vietnam, solide connaissance terrain/météo.",
      ],
      ru: [
        "Главный пилот; инструктор по парапланеризму и парашютному спорту в Покхаре.",
        "Главный пилот в Nepal Acro Paragliding.",
        "Бывший главный пилот в New Para World Paragliding.",
        "4 000+ часов профессиональных тандемных полётов, безопасность в приоритете.",
        "4+ года во Вьетнаме, отличные знания рельефа и погоды.",
      ],
      zh: [
        "波卡拉首席飞行员，滑翔伞与跳伞教练。",
        "Nepal Acro Paragliding 首席飞行员。",
        "曾任 New Para World Paragliding 首席飞行员。",
        "专业双人飞行 4,000+ 小时，始终把安全放第一。",
        "在越南工作 4+ 年，熟悉本地地形与天气。",
      ],
      hi: [
        "पोखरा में Chief Pilot; पैराग्लाइडिंग व स्काइडाइविंग इंस्ट्रक्टर।",
        "Nepal Acro Paragliding में Chief Pilot।",
        "New Para World Paragliding में पूर्व Chief Pilot।",
        "4,000+ घंटे प्रोफेशनल टैंडम उड़ान, सेफ़्टी फर्स्ट।",
        "वियतनाम में 4+ साल—टेर्रेन/मौसम की मजबूत समझ।",
      ],
    },
    flyingStyle: {
      vi: "Chuyến bay sống động, đầy cảm hứng âm nhạc, mượt mà và an toàn.",
      en: "Lively flights with musical vibes—smooth and safe.",
      fr: "Vols animés avec une touche musicale — fluides et sûrs.",
      ru: "Живые полёты с музыкальным вайбом — плавно и безопасно.",
      zh: "带着音乐氛围的活力飞行，顺滑又安全。",
      hi: "म्यूज़िक-वाइब वाली जीवंत फ्लाइट—स्मूद और सेफ़।",
    },
  },

  {
    slug: "dang-van-my",
    name: "Đặng Văn Mỹ",
    nickname: {
      vi: "Đội trưởng Mỹ",
      en: "Captain America",
      fr: "Captain America",
      ru: "Капитан Америка",
      zh: "美国队长",
      hi: "कैप्टन अमेरिका",
    },
    role: {
      vi: "Phi công trưởng, Phi công PG & PPG",
      en: "Chief Pilot, Paragliding & Powered Paragliding Pilot",
      fr: "Pilote en chef, Pilote parapente & paramoteur",
      ru: "Главный пилот, пилот параплана и парамотора",
      zh: "首席飞行员，滑翔伞/动力伞飞行员",
      hi: "चीफ पायलट, पैराग्लाइडिंग व पावर्ड पैराग्लाइडिंग पायलट",
    },
    experience: {
      vi: "10 năm",
      en: "10 years",
      fr: "10 ans",
      ru: "10 лет",
      zh: "10 年",
      hi: "10 साल",
    },
    flights: {
      vi: "7000+",
      en: "7000+",
      fr: "7000+",
      ru: "7000+",
      zh: "7000+",
      hi: "7000+",
    },
    hours: {
      vi: "Nhiều giờ",
      en: "Many hours",
      fr: "De nombreuses heures",
      ru: "Много часов",
      zh: "许多小时",
      hi: "कई घंटे",
    },
    phone: "0964073555",
    avatar: "/pilots/dang-van-my/dang-van-my.png",
    hero: "/pilots/hero.jpg",
    gallery: [
      "/pilots/dang-van-my/hero-1.png",
      "/pilots/dang-van-my/hero-2.png",
      "/pilots/dang-van-my/hero-3.png",
      "/pilots/dang-van-my/hero-4.png",
      "/pilots/dang-van-my/hero-5.png",
      "/pilots/dang-van-my/content-1.png",
      "/pilots/dang-van-my/content-2.png",
      "/pilots/dang-van-my/content-3.png",
    ],
    specialties: {
      vi: ["Heli", "Tumbling", "Dịch giả"],
      en: ["Heli", "Tumbling", "Translator"],
      fr: ["Heli", "Tumbling", "Traducteur"],
      ru: ["Heli", "Tumbling", "Переводчик"],
      zh: ["Heli", "Tumbling", "译者"],
      hi: ["Heli", "Tumbling", "अनुवादक"],
    },
    certificates: {
      vi: ["IPPI5 Nhật Bản"],
      en: ["Japan IPPI5"],
      fr: ["IPPI5 (Japon)"],
      ru: ["IPPI5 (Япония)"],
      zh: ["日本 IPPI5"],
      hi: ["जापान IPPI5"],
    },
    bio: {
      vi: "10 năm kinh nghiệm, 1,000+ chuyến bay đơn, 6,000+ chuyến bay đôi. Anh là phi công Heli đầu tiên tại Việt Nam và là phi công nhảy dây (tumbling) đầu tiên & duy nhất tại Việt Nam.",
      en: "10 years of experience, 1,000+ solo flights, 6,000+ tandem flights. The first Heli pilot in Vietnam and the first & only tumbling pilot in Vietnam.",
      fr: "10 ans d'expérience, 1 000+ vols solo, 6 000+ vols en tandem. Le premier pilote Heli au Vietnam et le premier & unique pilote de tumbling (voltige) au Vietnam.",
      ru: "10 лет опыта, 1 000+ одиночных полётов, 6 000+ тандемных. Первый Heli-пилот во Вьетнаме и первый и единственный пилот по тамблингу (акробатика) во Вьетнаме.",
      zh: "10 年经验，1,000+ 次单飞、6,000+ 次双人飞行。越南首位 Heli 飞行员，也是越南首位且唯一的 tumbling（绳索翻滚）飞行员。",
      hi: "10 साल का अनुभव, 1,000+ सोलो फ्लाइट्स, 6,000+ टैंडम फ्लाइट्स। वियतनाम के पहले Heli पायलट और पहले व इकलौते tumbling पायलट।",
    },
    funFacts: {
      vi: [
        "Khi ở dưới mặt đất, anh là người siêu kỷ luật với công việc và nhiệm vụ điều hành. Nhưng chỉ cần cất cánh, anh liền hoá thân thành người con của gió, mang theo niềm vui và truyền cảm hứng đam mê cho mọi hành khách bay cùng.",
      ],
      en: [
        "On the ground he’s highly disciplined in operations. Once airborne, he becomes a child of the wind—bringing joy and inspiring passion in every passenger.",
      ],
      fr: [
        "Au sol, très discipliné dans l’opérationnel. Dès le décollage, il devient un enfant du vent—joie et passion garanties.",
      ],
      ru: [
        "На земле — предельно дисциплинирован в работе. В воздухе — дитя ветра, дарящее радость и вдохновение каждому пассажиру.",
      ],
      zh: [
        "地面上他非常自律、负责运营；一旦起飞就像“风之子”，把快乐与热情带给每一位乘客。",
      ],
      hi: [
        "जमीन पर काम/ऑपरेशन्स में बेहद अनुशासित। लेकिन टेक-ऑफ होते ही ‘हवा के बच्चे’ बन जाते हैं—हर पैसेंजर को खुशी और पैशन से भर देते हैं।",
      ],
    },
    achievements: {
      vi: [
        "10 năm kinh nghiệm, 1,000+ chuyến bay đơn, 6,000+ chuyến bay đôi.",
        "Phi công Heli đầu tiên tại Việt Nam và Phi công nhảy dù (tumbling) đầu tiên & duy nhất tại Việt Nam. Anh có thể thực hiện các động tác mạnh với kỹ thuật cao và các động tác nhào lộn trên không hiếm có.",
        "Sở hữu kỹ năng bay dù lượn và dù lượn gắn động cơ.",
        "Dịch giả của hơn 1,000 trang sách chuyên sâu về dù lượn và là phi công nổi tiếng có kiến thức chuyên sâu về dù lượn. Anh sở hữu 03 đầu sách bán chạy nhất về dù lượn: Bay thermal, Bay đường trường và Thấu hiểu bầu trời.",
        "Dịch rất nhiều tài liệu bay, có nhiều kiến thức chuyên môn, phi công đầu tiên nhận chứng chỉ bay IPPI5 của Nhật Bản.",
        "Đang nắm giữ kỷ lục chuyến bay Tam giác khép kín lớn nhất tại Tây Nguyên 100+km và là phi công có nhiều giờ bay nhất Việt Nam.",
      ],
      en: [
        "10 years of experience, 1,000+ solo flights, 6,000+ tandem flights.",
        "First Heli pilot in Vietnam and the first & only tumbling pilot in Vietnam; capable of high-G maneuvers and rare aerial acrobatics.",
        "Skilled in both paragliding and powered paragliding.",
        "Translated 1,000+ pages of advanced paragliding books; author of 3 bestsellers: Thermal Flying, Cross-Country Flying, Understanding the Sky.",
        "Translated many technical documents; first pilot to receive Japan’s IPPI5 certificate.",
        "Holds the record for the largest closed triangle flight in the Central Highlands (100+ km) and is among Vietnam’s highest flight-hour pilots.",
      ],
      fr: [
        "10 ans d'expérience, 1 000+ vols solo, 6 000+ vols en tandem.",
        "Premier pilote Heli au Vietnam et premier & unique pilote de tumbling ; manœuvres à forte charge et acrobaties rares.",
        "Compétent en parapente et paramoteur.",
        "A traduit 1 000+ pages d’ouvrages techniques ; auteur de 3 best-sellers : Vol thermique, Vol de distance, Comprendre le ciel.",
        "Traducteur de nombreux documents ; premier pilote à obtenir la certification IPPI5 du Japon.",
        "Détient le record du plus grand triangle fermé aux Hauts Plateaux (100+ km) et fait partie des pilotes aux plus nombreuses heures de vol au Vietnam.",
      ],
      ru: [
        "10 лет опыта, 1 000+ одиночных полётов, 6 000+ тандемных.",
        "Первый Heli-пилот во Вьетнаме и первый/единственный пилот по тамблингу; способен на манёвры с высокими перегрузками и редкую акробатику.",
        "Владеет парапланом и моторным парапланом.",
        "Перевёл 1 000+ страниц специализированных книг; автор 3 бестселлеров: Thermal Flying, Cross-Country Flying, Understanding the Sky (переводы/издания).",
        "Перевёл множество материалов; первый пилот с сертификатом IPPI5 (Япония).",
        "Держит рекорд крупнейшего замкнутого треугольника на Центральном нагорье (100+ км) и входит в число пилотов с максимальным налётом во Вьетнаме.",
      ],
      zh: [
        "10 年经验，1,000+ 次单飞，6,000+ 次双人飞行。",
        "越南首位 Heli 飞行员、首位且唯一 tumbling 飞行员；可完成高 G 动作与罕见空中技巧。",
        "熟练掌握无动力与动力伞飞行。",
        "翻译 1,000+ 页专业书籍；著有 3 本热销书：热气流飞行、长距离飞行、理解天空。",
        "翻译大量飞行资料，专业知识深厚；越南首位获得日本 IPPI5 证书的飞行员。",
        "保持西原地区 100+ km 最大闭合三角航线纪录，也是越南飞行时长最多的飞行员之一。",
      ],
      hi: [
        "10 साल अनुभव, 1,000+ सोलो फ्लाइट्स, 6,000+ टैंडम फ्लाइट्स।",
        "वियतनाम के पहले Heli पायलट और पहले व इकलौते tumbling पायलट—हाई-G मैनूवर्स और दुर्लभ एरियल एक्रोबेटिक्स कर सकते हैं।",
        "पैराग्लाइडिंग और पावर्ड पैराग्लाइडिंग—दोनों में दक्ष।",
        "1,000+ पेज की एडवांस्ड पैराग्लाइडिंग पुस्तकों के अनुवादक; 3 बेस्टसेलर पुस्तकों के लेखक: Thermal Flying, Cross-Country Flying, Understanding the Sky।",
        "कई तकनीकी डॉक्यूमेंट्स का अनुवाद; जापान का IPPI5 सर्टिफिकेट पाने वाले पहले पायलट।",
        "Central Highlands में 100+ km का सबसे बड़ा closed triangle flight रिकॉर्ड; वियतनाम में सबसे ज़्यादा उड़ान घंटे रखने वाले पायलट्स में से एक।",
      ],
    },
    flyingStyle: {
      vi: "Kỹ thuật cao, thực hiện các động tác mạnh và nhào lộn hiếm có.",
      en: "High-level technique with strong maneuvers and rare acrobatics.",
      fr: "Haute technicité, manœuvres puissantes et acrobaties rares.",
      ru: "Высокая техника, сильные манёвры и редкая акробатика.",
      zh: "技术等级高，可完成强动作与罕见空中特技。",
      hi: "हाई-लेवल टेक्नीक, स्ट्रॉन्ग मैनूवर्स और दुर्लभ एक्रोबेटिक्स।",
    },
  },
];