// lib/booking/country-codes.ts
/**
 * Mã vùng điện thoại của mọi quốc gia, cho ô chọn ở bước 2 của luồng đặt bay.
 *
 * Trước đây chỉ có 12 nước hay gặp, nên khách Israel (+972), Malaysia, Ả Rập
 * Xê Út… không có mã của mình để chọn và phải bỏ dở việc đặt.
 *
 * Việt Nam đứng đầu danh sách, phần còn lại xếp theo tên nước.
 */

export type CountryCode = {
  /** Mã ISO 3166-1 alpha-2, dùng làm khoá vì mã vùng có thể trùng nhau. */
  iso: string;
  name: string;
  dial: string;
  flag: string;
};

export const COUNTRY_CODES: CountryCode[] = [
  { iso: "VN", name: "Việt Nam", dial: "+84", flag: "🇻🇳" },
  { iso: "AF", name: "Afghanistan", dial: "+93", flag: "🇦🇫" },
  { iso: "EG", name: "Ai Cập", dial: "+20", flag: "🇪🇬" },
  { iso: "AL", name: "Albania", dial: "+355", flag: "🇦🇱" },
  { iso: "DZ", name: "Algeria", dial: "+213", flag: "🇩🇿" },
  { iso: "AD", name: "Andorra", dial: "+376", flag: "🇦🇩" },
  { iso: "AO", name: "Angola", dial: "+244", flag: "🇦🇴" },
  { iso: "GB", name: "Anh", dial: "+44", flag: "🇬🇧" },
  { iso: "AG", name: "Antigua và Barbuda", dial: "+1268", flag: "🇦🇬" },
  { iso: "AR", name: "Argentina", dial: "+54", flag: "🇦🇷" },
  { iso: "AM", name: "Armenia", dial: "+374", flag: "🇦🇲" },
  { iso: "AW", name: "Aruba", dial: "+297", flag: "🇦🇼" },
  { iso: "AZ", name: "Azerbaijan", dial: "+994", flag: "🇦🇿" },
  { iso: "PL", name: "Ba Lan", dial: "+48", flag: "🇵🇱" },
  { iso: "BS", name: "Bahamas", dial: "+1242", flag: "🇧🇸" },
  { iso: "BH", name: "Bahrain", dial: "+973", flag: "🇧🇭" },
  { iso: "BD", name: "Bangladesh", dial: "+880", flag: "🇧🇩" },
  { iso: "BB", name: "Barbados", dial: "+1246", flag: "🇧🇧" },
  { iso: "BY", name: "Belarus", dial: "+375", flag: "🇧🇾" },
  { iso: "BZ", name: "Belize", dial: "+501", flag: "🇧🇿" },
  { iso: "BJ", name: "Benin", dial: "+229", flag: "🇧🇯" },
  { iso: "BM", name: "Bermuda", dial: "+1441", flag: "🇧🇲" },
  { iso: "BT", name: "Bhutan", dial: "+975", flag: "🇧🇹" },
  { iso: "BO", name: "Bolivia", dial: "+591", flag: "🇧🇴" },
  { iso: "BA", name: "Bosnia và Herzegovina", dial: "+387", flag: "🇧🇦" },
  { iso: "BW", name: "Botswana", dial: "+267", flag: "🇧🇼" },
  { iso: "BR", name: "Brazil", dial: "+55", flag: "🇧🇷" },
  { iso: "BN", name: "Brunei", dial: "+673", flag: "🇧🇳" },
  { iso: "BG", name: "Bulgaria", dial: "+359", flag: "🇧🇬" },
  { iso: "BF", name: "Burkina Faso", dial: "+226", flag: "🇧🇫" },
  { iso: "BI", name: "Burundi", dial: "+257", flag: "🇧🇮" },
  { iso: "MK", name: "Bắc Macedonia", dial: "+389", flag: "🇲🇰" },
  { iso: "BE", name: "Bỉ", dial: "+32", flag: "🇧🇪" },
  { iso: "PT", name: "Bồ Đào Nha", dial: "+351", flag: "🇵🇹" },
  { iso: "CI", name: "Bờ Biển Ngà", dial: "+225", flag: "🇨🇮" },
  { iso: "CV", name: "Cabo Verde", dial: "+238", flag: "🇨🇻" },
  { iso: "CM", name: "Cameroon", dial: "+237", flag: "🇨🇲" },
  { iso: "KH", name: "Campuchia", dial: "+855", flag: "🇰🇭" },
  { iso: "CA", name: "Canada", dial: "+1", flag: "🇨🇦" },
  { iso: "TD", name: "Chad", dial: "+235", flag: "🇹🇩" },
  { iso: "CD", name: "CHDC Congo", dial: "+243", flag: "🇨🇩" },
  { iso: "CL", name: "Chile", dial: "+56", flag: "🇨🇱" },
  { iso: "CO", name: "Colombia", dial: "+57", flag: "🇨🇴" },
  { iso: "KM", name: "Comoros", dial: "+269", flag: "🇰🇲" },
  { iso: "CG", name: "Congo", dial: "+242", flag: "🇨🇬" },
  { iso: "CR", name: "Costa Rica", dial: "+506", flag: "🇨🇷" },
  { iso: "HR", name: "Croatia", dial: "+385", flag: "🇭🇷" },
  { iso: "CU", name: "Cuba", dial: "+53", flag: "🇨🇺" },
  { iso: "DO", name: "Cộng hoà Dominica", dial: "+1809", flag: "🇩🇴" },
  { iso: "CF", name: "Cộng hoà Trung Phi", dial: "+236", flag: "🇨🇫" },
  { iso: "DJ", name: "Djibouti", dial: "+253", flag: "🇩🇯" },
  { iso: "DM", name: "Dominica", dial: "+1767", flag: "🇩🇲" },
  { iso: "EC", name: "Ecuador", dial: "+593", flag: "🇪🇨" },
  { iso: "SV", name: "El Salvador", dial: "+503", flag: "🇸🇻" },
  { iso: "ER", name: "Eritrea", dial: "+291", flag: "🇪🇷" },
  { iso: "EE", name: "Estonia", dial: "+372", flag: "🇪🇪" },
  { iso: "SZ", name: "Eswatini", dial: "+268", flag: "🇸🇿" },
  { iso: "ET", name: "Ethiopia", dial: "+251", flag: "🇪🇹" },
  { iso: "FJ", name: "Fiji", dial: "+679", flag: "🇫🇯" },
  { iso: "GA", name: "Gabon", dial: "+241", flag: "🇬🇦" },
  { iso: "GM", name: "Gambia", dial: "+220", flag: "🇬🇲" },
  { iso: "GE", name: "Georgia", dial: "+995", flag: "🇬🇪" },
  { iso: "GH", name: "Ghana", dial: "+233", flag: "🇬🇭" },
  { iso: "GI", name: "Gibraltar", dial: "+350", flag: "🇬🇮" },
  { iso: "GL", name: "Greenland", dial: "+299", flag: "🇬🇱" },
  { iso: "GD", name: "Grenada", dial: "+1473", flag: "🇬🇩" },
  { iso: "GU", name: "Guam", dial: "+1671", flag: "🇬🇺" },
  { iso: "GT", name: "Guatemala", dial: "+502", flag: "🇬🇹" },
  { iso: "GN", name: "Guinea", dial: "+224", flag: "🇬🇳" },
  { iso: "GQ", name: "Guinea Xích Đạo", dial: "+240", flag: "🇬🇶" },
  { iso: "GW", name: "Guinea-Bissau", dial: "+245", flag: "🇬🇼" },
  { iso: "GY", name: "Guyana", dial: "+592", flag: "🇬🇾" },
  { iso: "HT", name: "Haiti", dial: "+509", flag: "🇭🇹" },
  { iso: "US", name: "Hoa Kỳ", dial: "+1", flag: "🇺🇸" },
  { iso: "HN", name: "Honduras", dial: "+504", flag: "🇭🇳" },
  { iso: "HU", name: "Hungary", dial: "+36", flag: "🇭🇺" },
  { iso: "GR", name: "Hy Lạp", dial: "+30", flag: "🇬🇷" },
  { iso: "NL", name: "Hà Lan", dial: "+31", flag: "🇳🇱" },
  { iso: "KR", name: "Hàn Quốc", dial: "+82", flag: "🇰🇷" },
  { iso: "HK", name: "Hồng Kông", dial: "+852", flag: "🇭🇰" },
  { iso: "IS", name: "Iceland", dial: "+354", flag: "🇮🇸" },
  { iso: "ID", name: "Indonesia", dial: "+62", flag: "🇮🇩" },
  { iso: "IR", name: "Iran", dial: "+98", flag: "🇮🇷" },
  { iso: "IQ", name: "Iraq", dial: "+964", flag: "🇮🇶" },
  { iso: "IE", name: "Ireland", dial: "+353", flag: "🇮🇪" },
  { iso: "IL", name: "Israel", dial: "+972", flag: "🇮🇱" },
  { iso: "JM", name: "Jamaica", dial: "+1876", flag: "🇯🇲" },
  { iso: "JO", name: "Jordan", dial: "+962", flag: "🇯🇴" },
  { iso: "KZ", name: "Kazakhstan", dial: "+7", flag: "🇰🇿" },
  { iso: "KE", name: "Kenya", dial: "+254", flag: "🇰🇪" },
  { iso: "KI", name: "Kiribati", dial: "+686", flag: "🇰🇮" },
  { iso: "KW", name: "Kuwait", dial: "+965", flag: "🇰🇼" },
  { iso: "KG", name: "Kyrgyzstan", dial: "+996", flag: "🇰🇬" },
  { iso: "LV", name: "Latvia", dial: "+371", flag: "🇱🇻" },
  { iso: "LS", name: "Lesotho", dial: "+266", flag: "🇱🇸" },
  { iso: "LB", name: "Liban", dial: "+961", flag: "🇱🇧" },
  { iso: "LR", name: "Liberia", dial: "+231", flag: "🇱🇷" },
  { iso: "LY", name: "Libya", dial: "+218", flag: "🇱🇾" },
  { iso: "LI", name: "Liechtenstein", dial: "+423", flag: "🇱🇮" },
  { iso: "LT", name: "Litva", dial: "+370", flag: "🇱🇹" },
  { iso: "LU", name: "Luxembourg", dial: "+352", flag: "🇱🇺" },
  { iso: "LA", name: "Lào", dial: "+856", flag: "🇱🇦" },
  { iso: "MO", name: "Ma Cao", dial: "+853", flag: "🇲🇴" },
  { iso: "MG", name: "Madagascar", dial: "+261", flag: "🇲🇬" },
  { iso: "MW", name: "Malawi", dial: "+265", flag: "🇲🇼" },
  { iso: "MY", name: "Malaysia", dial: "+60", flag: "🇲🇾" },
  { iso: "MV", name: "Maldives", dial: "+960", flag: "🇲🇻" },
  { iso: "ML", name: "Mali", dial: "+223", flag: "🇲🇱" },
  { iso: "MT", name: "Malta", dial: "+356", flag: "🇲🇹" },
  { iso: "MA", name: "Maroc", dial: "+212", flag: "🇲🇦" },
  { iso: "MR", name: "Mauritania", dial: "+222", flag: "🇲🇷" },
  { iso: "MU", name: "Mauritius", dial: "+230", flag: "🇲🇺" },
  { iso: "MX", name: "Mexico", dial: "+52", flag: "🇲🇽" },
  { iso: "FM", name: "Micronesia", dial: "+691", flag: "🇫🇲" },
  { iso: "MD", name: "Moldova", dial: "+373", flag: "🇲🇩" },
  { iso: "MC", name: "Monaco", dial: "+377", flag: "🇲🇨" },
  { iso: "ME", name: "Montenegro", dial: "+382", flag: "🇲🇪" },
  { iso: "MZ", name: "Mozambique", dial: "+258", flag: "🇲🇿" },
  { iso: "MM", name: "Myanmar", dial: "+95", flag: "🇲🇲" },
  { iso: "MN", name: "Mông Cổ", dial: "+976", flag: "🇲🇳" },
  { iso: "NO", name: "Na Uy", dial: "+47", flag: "🇳🇴" },
  { iso: "ZA", name: "Nam Phi", dial: "+27", flag: "🇿🇦" },
  { iso: "SS", name: "Nam Sudan", dial: "+211", flag: "🇸🇸" },
  { iso: "NA", name: "Namibia", dial: "+264", flag: "🇳🇦" },
  { iso: "NR", name: "Nauru", dial: "+674", flag: "🇳🇷" },
  { iso: "NP", name: "Nepal", dial: "+977", flag: "🇳🇵" },
  { iso: "NZ", name: "New Zealand", dial: "+64", flag: "🇳🇿" },
  { iso: "RU", name: "Nga", dial: "+7", flag: "🇷🇺" },
  { iso: "JP", name: "Nhật Bản", dial: "+81", flag: "🇯🇵" },
  { iso: "NI", name: "Nicaragua", dial: "+505", flag: "🇳🇮" },
  { iso: "NE", name: "Niger", dial: "+227", flag: "🇳🇪" },
  { iso: "NG", name: "Nigeria", dial: "+234", flag: "🇳🇬" },
  { iso: "NC", name: "Nouvelle-Calédonie", dial: "+687", flag: "🇳🇨" },
  { iso: "OM", name: "Oman", dial: "+968", flag: "🇴🇲" },
  { iso: "PK", name: "Pakistan", dial: "+92", flag: "🇵🇰" },
  { iso: "PW", name: "Palau", dial: "+680", flag: "🇵🇼" },
  { iso: "PS", name: "Palestine", dial: "+970", flag: "🇵🇸" },
  { iso: "PA", name: "Panama", dial: "+507", flag: "🇵🇦" },
  { iso: "PG", name: "Papua New Guinea", dial: "+675", flag: "🇵🇬" },
  { iso: "PY", name: "Paraguay", dial: "+595", flag: "🇵🇾" },
  { iso: "PE", name: "Peru", dial: "+51", flag: "🇵🇪" },
  { iso: "PH", name: "Philippines", dial: "+63", flag: "🇵🇭" },
  { iso: "FR", name: "Pháp", dial: "+33", flag: "🇫🇷" },
  { iso: "FI", name: "Phần Lan", dial: "+358", flag: "🇫🇮" },
  { iso: "PR", name: "Puerto Rico", dial: "+1787", flag: "🇵🇷" },
  { iso: "QA", name: "Qatar", dial: "+974", flag: "🇶🇦" },
  { iso: "KY", name: "Quần đảo Cayman", dial: "+1345", flag: "🇰🇾" },
  { iso: "MH", name: "Quần đảo Marshall", dial: "+692", flag: "🇲🇭" },
  { iso: "SB", name: "Quần đảo Solomon", dial: "+677", flag: "🇸🇧" },
  { iso: "RO", name: "Romania", dial: "+40", flag: "🇷🇴" },
  { iso: "RW", name: "Rwanda", dial: "+250", flag: "🇷🇼" },
  { iso: "RE", name: "Réunion", dial: "+262", flag: "🇷🇪" },
  { iso: "KN", name: "Saint Kitts và Nevis", dial: "+1869", flag: "🇰🇳" },
  { iso: "LC", name: "Saint Lucia", dial: "+1758", flag: "🇱🇨" },
  { iso: "VC", name: "Saint Vincent và Grenadines", dial: "+1784", flag: "🇻🇨" },
  { iso: "WS", name: "Samoa", dial: "+685", flag: "🇼🇸" },
  { iso: "SM", name: "San Marino", dial: "+378", flag: "🇸🇲" },
  { iso: "SN", name: "Senegal", dial: "+221", flag: "🇸🇳" },
  { iso: "RS", name: "Serbia", dial: "+381", flag: "🇷🇸" },
  { iso: "SC", name: "Seychelles", dial: "+248", flag: "🇸🇨" },
  { iso: "SL", name: "Sierra Leone", dial: "+232", flag: "🇸🇱" },
  { iso: "SG", name: "Singapore", dial: "+65", flag: "🇸🇬" },
  { iso: "SK", name: "Slovakia", dial: "+421", flag: "🇸🇰" },
  { iso: "SI", name: "Slovenia", dial: "+386", flag: "🇸🇮" },
  { iso: "SO", name: "Somalia", dial: "+252", flag: "🇸🇴" },
  { iso: "LK", name: "Sri Lanka", dial: "+94", flag: "🇱🇰" },
  { iso: "SD", name: "Sudan", dial: "+249", flag: "🇸🇩" },
  { iso: "SR", name: "Suriname", dial: "+597", flag: "🇸🇷" },
  { iso: "SY", name: "Syria", dial: "+963", flag: "🇸🇾" },
  { iso: "CZ", name: "Séc", dial: "+420", flag: "🇨🇿" },
  { iso: "CY", name: "Síp", dial: "+357", flag: "🇨🇾" },
  { iso: "TJ", name: "Tajikistan", dial: "+992", flag: "🇹🇯" },
  { iso: "TZ", name: "Tanzania", dial: "+255", flag: "🇹🇿" },
  { iso: "CH", name: "Thuỵ Sĩ", dial: "+41", flag: "🇨🇭" },
  { iso: "SE", name: "Thuỵ Điển", dial: "+46", flag: "🇸🇪" },
  { iso: "TH", name: "Thái Lan", dial: "+66", flag: "🇹🇭" },
  { iso: "TR", name: "Thổ Nhĩ Kỳ", dial: "+90", flag: "🇹🇷" },
  { iso: "TG", name: "Togo", dial: "+228", flag: "🇹🇬" },
  { iso: "TO", name: "Tonga", dial: "+676", flag: "🇹🇴" },
  { iso: "TT", name: "Trinidad và Tobago", dial: "+1868", flag: "🇹🇹" },
  { iso: "KP", name: "Triều Tiên", dial: "+850", flag: "🇰🇵" },
  { iso: "CN", name: "Trung Quốc", dial: "+86", flag: "🇨🇳" },
  { iso: "TN", name: "Tunisia", dial: "+216", flag: "🇹🇳" },
  { iso: "TM", name: "Turkmenistan", dial: "+993", flag: "🇹🇲" },
  { iso: "ES", name: "Tây Ban Nha", dial: "+34", flag: "🇪🇸" },
  { iso: "AE", name: "UAE", dial: "+971", flag: "🇦🇪" },
  { iso: "UG", name: "Uganda", dial: "+256", flag: "🇺🇬" },
  { iso: "UA", name: "Ukraina", dial: "+380", flag: "🇺🇦" },
  { iso: "UY", name: "Uruguay", dial: "+598", flag: "🇺🇾" },
  { iso: "UZ", name: "Uzbekistan", dial: "+998", flag: "🇺🇿" },
  { iso: "VU", name: "Vanuatu", dial: "+678", flag: "🇻🇺" },
  { iso: "VA", name: "Vatican", dial: "+379", flag: "🇻🇦" },
  { iso: "VE", name: "Venezuela", dial: "+58", flag: "🇻🇪" },
  { iso: "YE", name: "Yemen", dial: "+967", flag: "🇾🇪" },
  { iso: "ZM", name: "Zambia", dial: "+260", flag: "🇿🇲" },
  { iso: "ZW", name: "Zimbabwe", dial: "+263", flag: "🇿🇼" },
  { iso: "AT", name: "Áo", dial: "+43", flag: "🇦🇹" },
  { iso: "AU", name: "Úc", dial: "+61", flag: "🇦🇺" },
  { iso: "IT", name: "Ý", dial: "+39", flag: "🇮🇹" },
  { iso: "DK", name: "Đan Mạch", dial: "+45", flag: "🇩🇰" },
  { iso: "TW", name: "Đài Loan", dial: "+886", flag: "🇹🇼" },
  { iso: "TL", name: "Đông Timor", dial: "+670", flag: "🇹🇱" },
  { iso: "DE", name: "Đức", dial: "+49", flag: "🇩🇪" },
  { iso: "SA", name: "Ả Rập Xê Út", dial: "+966", flag: "🇸🇦" },
  { iso: "IN", name: "Ấn Độ", dial: "+91", flag: "🇮🇳" },
];

/**
 * Tách mã vùng ra khỏi số điện thoại đã lưu.
 *
 * Phải thử mã DÀI TRƯỚC: "+1268" (Antigua) cũng bắt đầu bằng "+1" (Hoa Kỳ),
 * so từ đầu danh sách sẽ luôn ra nhầm nước có mã ngắn hơn.
 */
/**
 * Nước được ưu tiên khi nhiều nước dùng chung một mã vùng: "+1" là của cả
 * Hoa Kỳ lẫn Canada, "+7" của cả Nga lẫn Kazakhstan. Không chốt thì số đã lưu
 * hiện ra tên nước ít gặp hơn.
 */
const PRIMARY_FOR_DIAL: Record<string, string> = {
  "+1": "US",
  "+7": "RU",
};

const BY_LENGTH = [...COUNTRY_CODES].sort((a, b) => {
  if (a.dial.length !== b.dial.length) return b.dial.length - a.dial.length;
  if (PRIMARY_FOR_DIAL[a.dial] === a.iso) return -1;
  if (PRIMARY_FOR_DIAL[b.dial] === b.iso) return 1;
  return 0;
});

export function matchCountryCode(raw: string): CountryCode | undefined {
  const value = String(raw ?? "").trim();
  return BY_LENGTH.find((c) => value.startsWith(c.dial));
}
